<a href="https://colab.research.google.com/github/kunj1674/Colab_Project/blob/master/Data_Cleaning_Practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>


You have been hired by a rookie movie producer to help him decide what type of movies to produce and which actors to cast. You have to back your recommendations based on thorough analysis of the data he shared with you which has the list of 3000 movies and the corresponding details.


As a data scientist, you have to first explore the data and check its sanity.  
Further, you have to answer the following questions:

1.Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.

2.This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)?

3.Find out the unique genres of movies in this dataset.

4.Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor.

Data Exploration

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/imdb_data.csv')

In [5]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [7]:
df['profit']=df['revenue']-df['budget']
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'profit'],
      dtype='object')

In [8]:
df[df['profit']==df['profit'].max()][['title']]

          title
1761  Furious 7

In [9]:
df[df['profit']==df['profit'].max()][['cast']]

                                                   cast
1761  [{'cast_id': 17, 'character': 'Dominic Toretto...

In [10]:
df[df['profit']==df['profit'].max()][['crew']].values[0][0]

'[{\'credit_id\': \'52fe4cc8c3a36847f823e681\', \'department\': \'Production\', \'gender\': 2, \'id\': 12835, \'job\': \'Producer\', \'name\': \'Vin Diesel\', \'profile_path\': \'/7rwSXluNWZAluYMOEWBxkPmckES.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e687\', \'department\': \'Production\', \'gender\': 2, \'id\': 11874, \'job\': \'Producer\', \'name\': \'Neal H. Moritz\', \'profile_path\': \'/cNcsEYmoS4niCz3UkVAA09dUIob.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e68d\', \'department\': \'Writing\', \'gender\': 2, \'id\': 58191, \'job\': \'Writer\', \'name\': \'Chris Morgan\', \'profile_path\': \'/dUGxIwFBLrSFLImxjeda1krndMO.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e693\', \'department\': \'Writing\', \'gender\': 0, \'id\': 8162, \'job\': \'Characters\', \'name\': \'Gary Scott Thompson\', \'profile_path\': \'/e2dMfqFvRsOXgWZ1VToYLmos17y.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e699\', \'department\': \'Directing\', \'gender\': 2, \'id\': 2127, \'job\': \'Director\', \'name\': \'James Wan\', \'profile_path\': \'/d1LSKfzi5J6QngWS7niN1zPJdud.jpg\'}, {\'credit_id\': \'52fe4cc8c3a36847f823e6a7\', \'department\': \'Camera\', \'gender\': 2, \'id\': 58192, \'job\': \'Director of Photography\', \'name\': \'Stephen F. Windon\', \'profile_path\': None}, {\'credit_id\': \'5534714692514125dc002be4\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1455610, \'job\': \'Animation\', \'name\': \'Tony Mecca\', \'profile_path\': None}, {\'credit_id\': \'554fa7b992514110bd002a9d\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1421687, \'job\': \'Director of Photography\', \'name\': \'Marc Spicer\', \'profile_path\': None}, {\'credit_id\': \'554fa7cbc3a36822540047fd\', \'department\': \'Production\', \'gender\': 1, \'id\': 90635, \'job\': \'Executive Producer\', \'name\': \'Samantha Vincent\', \'profile_path\': None}, {\'credit_id\': \'554fa7d89251413fcf00773d\', \'department\': \'Production\', \'gender\': 0, \'id\': 84064, \'job\': \'Associate Producer\', \'name\': \'F. Valentino Morales\', \'profile_path\': \'/w85eCnNP0VgmfV5NWyq2SvRGi2y.jpg\'}, {\'credit_id\': \'554fa7f2c3a3682254004803\', \'department\': \'Production\', \'gender\': 2, \'id\': 8181, \'job\': \'Producer\', \'name\': \'Michael Fottrell\', \'profile_path\': None}, {\'credit_id\': \'554fa80292514110bd002aa8\', \'department\': \'Production\', \'gender\': 0, \'id\': 75826, \'job\': \'Producer\', \'name\': \'Brandon Birtell\', \'profile_path\': None}, {\'credit_id\': \'55ed993ac3a3682c62015607\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1204244, \'job\': \'Editor\', \'name\': \'Leigh Folsom Boyd\', \'profile_path\': None}, {\'credit_id\': \'55ed994cc3a3687d3b00d64c\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1204245, \'job\': \'Editor\', \'name\': \'Dylan Highsmith\', \'profile_path\': None}, {\'credit_id\': \'55ed995dc3a3682c5d016867\', \'department\': \'Editing\', \'gender\': 0, \'id\': 62813, \'job\': \'Editor\', \'name\': \'Kirk M. Morri\', \'profile_path\': None}, {\'credit_id\': \'55ed99739251413e41014641\', \'department\': \'Editing\', \'gender\': 2, \'id\': 6668, \'job\': \'Editor\', \'name\': \'Christian Wagner\', \'profile_path\': None}, {\'credit_id\': \'55ed99859251413e3a014aae\', \'department\': \'Production\', \'gender\': 1, \'id\': 9545, \'job\': \'Casting\', \'name\': \'Anne McCarthy\', \'profile_path\': None}, {\'credit_id\': \'55ed99a4c3a3682c5d016875\', \'department\': \'Production\', \'gender\': 0, \'id\': 1276602, \'job\': \'Casting\', \'name\': \'Kellie Roy\', \'profile_path\': None}, {\'credit_id\': \'55ed99c7c3a3682c5d01687e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1445830, \'job\': \'Art Direction\', \'name\': \'Jonathan Carlos\', \'profile_path\': None}, {\'credit_id\': \'55ed99d89251413e32014a65\', \'department\': \'Art\', \'gender\': 2, \'id\': 62780, \'job\': \'Art Direction\', \'name\': \'Alan Hook\', \'profile_path\': None}, {\'credit_id\': \'55ed99e992514106d600d85e\', \'department\': \'Art\', \'gender\': 0, \'id\': 1493864, \'job\': \'Art Direction\', \'name\': \'Jay Pelissier\', \'profile_path\': None}, {\'credit_id\': \'55ed9a36c3a3682c700147e3\', \'department\': \'Art\', \'gender\': 1, \'id\': 1506359, \'job\': \'Art Department Coordinator\', \'name\': \'Kelly Richardson\', \'profile_path\': None}, {\'credit_id\': \'55ed9a52c3a3682c640130c3\', \'department\': \'Art\', \'gender\': 0, \'id\': 1506360, \'job\': \'Art Department Coordinator\', \'name\': \'Courtney Cocherell\', \'profile_path\': None}, {\'credit_id\': \'55ed9a6cc3a368090c004f9c\', \'department\': \'Art\', \'gender\': 0, \'id\': 1326651, \'job\': \'Assistant Art Director\', \'name\': \'Elena Albanese\', \'profile_path\': None}, {\'credit_id\': \'55ed9a96c3a3686f17003be1\', \'department\': \'Art\', \'gender\': 0, \'id\': 1405376, \'job\': \'Assistant Art Director\', \'name\': \'Alex McCarroll\', \'profile_path\': None}, {\'credit_id\': \'55ed9acbc3a3682c640130e4\', \'department\': \'Art\', \'gender\': 0, \'id\': 1338147, \'job\': \'Construction Coordinator\', \'name\': \'Bruce Di Valerio\', \'profile_path\': None}, {\'credit_id\': \'55ed9b03c3a3682c640130f5\', \'department\': \'Art\', \'gender\': 2, \'id\': 52600, \'job\': \'Production Design\', \'name\': \'Bill Brzeski\', \'profile_path\': None}, {\'credit_id\': \'55ed9b169251413e2f0145a8\', \'department\': \'Art\', \'gender\': 1, \'id\': 75391, \'job\': \'Set Decoration\', \'name\': \'Danielle Berman\', \'profile_path\': None}, {\'credit_id\': \'55ed9b29c3a3682c5d0168d9\', \'department\': \'Costume & Make-Up\', \'gender\': 1, \'id\': 2519, \'job\': \'Costume Design\', \'name\': \'Sanja Milkovic Hays\', \'profile_path\': None}, {\'credit_id\': \'55ed9bdac3a3682c62015698\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1439109, \'job\': \'Costume Supervisor\', \'name\': \'Nava R. Sadan\', \'profile_path\': None}, {\'credit_id\': \'55ed9c0bc3a3686f17003c45\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1439747, \'job\': \'Costume Supervisor\', \'name\': \'Andrew Hunt\', \'profile_path\': None}, {\'credit_id\': \'55ed9c3192514106d600d8e0\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506364, \'job\': \'Set Costumer\', \'name\': \'Jim Alan Cook\', \'profile_path\': None}, {\'credit_id\': \'55ed9c45c3a3682c5d016925\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1415019, \'job\': \'Set Costumer\', \'name\': \'Shayne Allen Duhon\', \'profile_path\': None}, {\'credit_id\': \'55ed9c579251413e32014af5\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506365, \'job\': \'Set Costumer\', \'name\': \'Empress Holley\', \'profile_path\': None}, {\'credit_id\': \'55ed9c6d9251413e450148ff\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1413125, \'job\': \'Set Costumer\', \'name\': \'Marina Marit\', \'profile_path\': None}, {\'credit_id\': \'55ed9c8d92514106d600d8fb\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506366, \'job\': \'Set Costumer\', \'name\': \'Les Morgan\', \'profile_path\': None}, {\'credit_id\': \'55ed9cda9251413e2f014612\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1408293, \'job\': \'Hairstylist\', \'name\': \'Linda D. Flowers\', \'profile_path\': None}, {\'credit_id\': \'55ed9cf69251413e2f01461d\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1412767, \'job\': \'Hairstylist\', \'name\': "Yesim \'Shimmy\' Osman", \'profile_path\': None}, {\'credit_id\': \'55ed9d0ec3a3687d3b00d73a\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506367, \'job\': \'Hairstylist\', \'name\': \'Jennifer Santiago\', \'profile_path\': None}, {\'credit_id\': \'55ed9d2a9251413e3e0155d8\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1425409, \'job\': \'Hairstylist\', \'name\': \'Rachel Solow\', \'profile_path\': None}, {\'credit_id\': \'55ed9d4cc3a3682c620156ed\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1452643, \'job\': \'Hairstylist\', \'name\': \'Roxane Griffin\', \'profile_path\': None}, {\'credit_id\': \'55ed9d6fc3a3682c5d01696f\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1309209, \'job\': \'Makeup Department Head\', \'name\': \'James MacKinnon\', \'profile_path\': None}, {\'credit_id\': \'55ed9d8cc3a368090c00504f\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506368, \'job\': \'Makeup Artist\', \'name\': \'Autumn Butler\', \'profile_path\': None}, {\'credit_id\': \'55ed9da09251413e3a014b98\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1437798, \'job\': \'Makeup Artist\', \'name\': "Roxy D\'Alonzo", \'profile_path\': None}, {\'credit_id\': \'55ed9db79251413e3a014ba5\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1506369, \'job\': \'Makeup Artist\', \'name\': \'Hee Soo Kwon\', \'profile_path\': None}, {\'credit_id\': \'55ed9dce9251413e32014b4e\', \'department\': \'Costume & Make-Up\', \'gender\': 1, \'id\': 1459196, \'job\': \'Makeup Artist\', \'name\': \'Sarah Mays\', \'profile_path\': None}, {\'credit_id\': \'55ed9de4c3a3687d3b00d775\', \'department\': \'Costume & Make-Up\', \'gender\': 2, \'id\': 15330, \'job\': \'Makeup Artist\', \'name\': \'Paul Pattison\', \'profile_path\': None}, {\'credit_id\': \'55ed9df99251413e3e015610\', \'department\': \'Costume & Make-Up\', \'gender\': 0, \'id\': 1317667, \'job\': \'Makeup Artist\', \'name\': \'Eleanor Sabaduquia\', \'profile_path\': None}, {\'credit_id\': \'55ed9e1fc3a3687d3b00d77e\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1414497, \'job\': \'Property Master\', \'name\': \'Guillaume DeLouche\', \'profile_path\': None}, {\'credit_id\': \'55ed9e3ac3a368090c005084\', \'department\': \'Crew\', \'gender\': 0, \'id\': 1464516, \'job\': \'Property Master\', \'name\': \'Douglas T. Madison\', \'profile_path\': None}, {\'credit_id\': \'55ed9f5d9251413e3e015662\', \'department\': \'Crew\', \'gender\': 2, \'id\': 57158, \'job\': \'Second Unit Cinematographer\', \'name\': \'Igor Meglic\', \'profile_path\': None}, {\'credit_id\': \'55ed9fa0c3a3682c6401320f\', \'department\': \'Crew\', \'gender\': 0, \'id\': 13670, \'job\': \'Second Unit Cinematographer\', \'name\': \'Jacques Haitkin\', \'profile_path\': None}, {\'credit_id\': \'55ed9fc59251413e32014bbc\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1437304, \'job\': \'Gaffer\', \'name\': \'Michael Ambrose\', \'profile_path\': None}, {\'credit_id\': \'55ed9fe79251413e410147e4\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1506371, \'job\': \'Camera Operator\', \'name\': \'Denise Bailie\', \'profile_path\': None}, {\'credit_id\': \'55ed9ffa9251413e3a014c40\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1506373, \'job\': \'Camera Operator\', \'name\': \'Robert-James Bova\', \'profile_path\': None}, {\'credit_id\': \'55eda0299251413e3a014c49\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1439108, \'job\': \'Rigging Gaffer\', \'name\': \'Tom Fendley\', \'profile_path\': None}, {\'credit_id\': \'55eda056c3a3682c7001494b\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1434896, \'job\': \'Camera Operator\', \'name\': \'Sarah Levy\', \'profile_path\': None}, {\'credit_id\': \'55eda06e9251413e450149ee\', \'department\': \'Camera\', \'gender\': 2, \'id\': 74989, \'job\': \'Camera Operator\', \'name\': \'Mark Emery Moore\', \'profile_path\': \'/mhjX0FuAXv6SeSLLFHpaaiQbx6P.jpg\'}, {\'credit_id\': \'55eda082c3a3682c6b014009\', \'department\': \'Camera\', \'gender\': 2, \'id\': 1432918, \'job\': \'Camera Operator\', \'name\': \'Daniel Nichols\', \'profile_path\': None}, {\'credit_id\': \'55eda09d9251413e3e01569d\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1439104, \'job\': \'Camera Operator\', \'name\': \'Onofrio Nino Pansini\', \'profile_path\': None}, {\'credit_id\': \'55eda0b59251413e3a014c6c\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1408356, \'job\': \'Camera Operator\', \'name\': \'David Richert\', \'profile_path\': None}, {\'credit_id\': \'55eda0d1c3a3686f17003d58\', \'department\': \'Camera\', \'gender\': 2, \'id\': 1411271, \'job\': \'Camera Operator\', \'name\': \'Michael J. Walker\', \'profile_path\': None}, {\'credit_id\': \'55eda0f7c3a3687d3b00d81b\', \'department\': \'Camera\', \'gender\': 2, \'id\': 1378241, \'job\': \'Camera Operator\', \'name\': \'Maurice K. McGuire\', \'profile_path\': None}, {\'credit_id\': \'55eda1159251413e3e0156bd\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1411842, \'job\': \'Camera Operator\', \'name\': \'Richard Latham\', \'profile_path\': None}, {\'credit_id\': \'55eda12c92514106d600da0a\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1404739, \'job\': \'Helicopter Camera\', \'name\': \'Steve Koster\', \'profile_path\': None}, {\'credit_id\': \'55eda1939251413e3501498d\', \'department\': \'Camera\', \'gender\': 0, \'id\': 91122, \'job\': \'Helicopter Camera\', \'name\': \'Dylan Goss\', \'profile_path\': None}, {\'credit_id\': \'55eda1b39251413e3a014ca8\', \'department\': \'Camera\', \'gender\': 0, \'id\': 82169, \'job\': \'Steadicam Operator\', \'name\': \'Geoffrey Haley\', \'profile_path\': None}, {\'credit_id\': \'55eda1c7c3a3686f17003d8c\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1419105, \'job\': \'Still Photographer\', \'name\': \'Scott Garfield\', \'profile_path\': None}, {\'credit_id\': \'55eda1dbc3a3686f17003d92\', \'department\': \'Camera\', \'gender\': 2, \'id\': 1395281, \'job\': \'Additional Camera\', \'name\': \'Bob Gorelick\', \'profile_path\': None}, {\'credit_id\': \'55eda200c3a3682c5d016a8f\', \'department\': \'Camera\', \'gender\': 0, \'id\': 1375920, \'job\': \'Additional Camera\', \'name\': \'J. Christopher Campbell\', \'profile_path\': None}, {\'credit_id\': \'55eda228c3a3682c64013295\', \'department\': \'Lighting\', \'gender\': 0, \'id\': 1403412, \'job\': \'Gaffer\', \'name\': \'Dan Cornwall\', \'profile_path\': None}, {\'credit_id\': \'55eda25f92514106d600da4b\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1442137, \'job\': \'Animation Supervisor\', \'name\': \'Catherine Mullan\', \'profile_path\': None}, {\'credit_id\': \'55eda292c3a3682c5d016ab2\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1393405, \'job\': \'Music Editor\', \'name\': \'Robb Boyd\', \'profile_path\': None}, {\'credit_id\': \'55eda2a9c3a3682c6b014075\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1328758, \'job\': \'Music Editor\', \'name\': \'Matthew Llewellyn\', \'profile_path\': None}, {\'credit_id\': \'55eda2c89251413e45014a6d\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1389138, \'job\': \'Script Supervisor\', \'name\': \'Jody Blose\', \'profile_path\': None}, {\'credit_id\': \'55eda305c3a3682c700149c1\', \'department\': \'Directing\', \'gender\': 0, \'id\': 1408365, \'job\': \'Script Supervisor\', \'name\': \'Brenda K. Wachel\', \'profile_path\': None}, {\'credit_id\': \'55eda32dc3a3686f17003ddd\', \'department\': \'Crew\', \'gender\': 2, \'id\': 8167, \'job\': \'Thanks\', \'name\': \'Paul Walker\', \'profile_path\': \'/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg\'}, {\'credit_id\': \'55eda3b592514106d600da94\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1400354, \'job\': \'Digital Intermediate\', \'name\': \'Amy Pawlowski\', \'profile_path\': None}, {\'credit_id\': \'55eda3d792514106d600da9b\', \'department\': \'Editing\', \'gender\': 0, \'id\': 110262, \'job\': \'First Assistant Editor\', \'name\': \'Richard Conkling\', \'profile_path\': None}, {\'credit_id\': \'55eda3edc3a3686f17003e0c\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1194885, \'job\': \'First Assistant Editor\', \'name\': \'Dave  Cory\', \'profile_path\': None}, {\'credit_id\': \'55eda4169251413e410148ec\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1439749, \'job\': \'First Assistant Editor\', \'name\': \'Laura Steiger\', \'profile_path\': None}, {\'credit_id\': \'55eda48092514106d600daba\', \'department\': \'Visual Effects\', \'gender\': 0, \'id\': 1506377, \'job\': \'Animation Supervisor\', \'name\': \'Daniel Barrett\', \'profile_path\': \'/pplTJP3gCWmP3SMDrXjOt1579MV.jpg\'}, {\'credit_id\': \'55eda5109251413e32014cf0\', \'department\': \'Sound\', \'gender\': 0, \'id\': 12562, \'job\': \'ADR & Dubbing\', \'name\': \'Anna MacKenzie\', \'profile_path\': None}, {\'credit_id\': \'55eda51ac3a3686f17003e52\', \'department\': \'Editing\', \'gender\': 0, \'id\': 12562, \'job\': \'Dialogue Editor\', \'name\': \'Anna MacKenzie\', \'profile_path\': None}, {\'credit_id\': \'55eda539c3a368090c0051c2\', \'department\': \'Editing\', \'gender\': 0, \'id\': 1342658, \'job\': \'Dialogue Editor\', \'name\': \'Frederick H. Stahly\', \'profile_path\': None}, {\'credit_id\': \'55eda56a9251413e45014adf\', \'department\': \'Sound\', \'gender\': 2, \'id\': 1077782, \'job\': \'Foley\', \'name\': \'Gary A. Hecker\', \'profile_path\': \'/qyBUauN3XIS2Mlus3OdGCmrUo0S.jpg\'}, {\'credit_id\': \'55eda58292514106d600daf4\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1367362, \'job\': \'Foley\', \'name\': \'Rick Owens\', \'profile_path\': None}, {\'credit_id\': \'55eda59ac3a3682c5d016b50\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1236340, \'job\': \'Foley\', \'name\': \'Dylan Tuomy-Wilhoit\', \'profile_path\': None}, {\'credit_id\': \'55eda5b09251413e45014af1\', \'department\': \'Sound\', \'gender\': 0, \'id\': 548445, \'job\': \'Foley\', \'name\': \'Jeffrey Wilhoit\', \'profile_path\': None}, {\'credit_id\': \'55eda7169251413e45014b3b\', \'department\': \'Sound\', \'gender\': 2, \'id\': 7239, \'job\': \'Sound Designer\', \'name\': \'Peter Brown\', \'profile_path\': None}, {\'credit_id\': \'55eda73d9251413e4101498c\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1392083, \'job\': \'Sound Designer\', \'name\': \'Ann Scibelli\', \'profile_path\': None}, {\'credit_id\': \'55eda779c3a3682c70014abc\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1413453, \'job\': \'Sound Effects Editor\', \'name\': \'Stephen P. Robinson\', \'profile_path\': None}, {\'credit_id\': \'55eda7989251413e3e015838\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1394131, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Jon Taylor\', \'profile_path\': None}, {\'credit_id\': \'55eda7afc3a3686f17003ebf\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1394130, \'job\': \'Sound Re-Recording Mixer\', \'name\': \'Frank A. Monta√±o\', \'profile_path\': None}, {\'credit_id\': \'55eda7d79251413e32014e11\', \'department\': \'Sound\', \'gender\': 0, \'id\': 1309884, \'job\': \'Supervising Sound Editor\', \'name\': \'Joe Dzuban\', \'profile_path\': None}, {\'credit_id\': \'570bd40dc3a36802a30002d9\', \'department\': \'Art\', \'gender\': 0, \'id\': 1424153, \'job\': \'Supervising Art Director\', \'name\': \'Desma Murphy\', \'profile_path\': None}, {\'credit_id\': \'5668cc7a92514174040040f2\', \'department\': \'Sound\', \'gender\': 2, \'id\': 6041, \'job\': \'Original Music Composer\', \'name\': \'Brian Tyler\', \'profile_path\': \'/22QWiNJj03amY6GT1QPUs7dbdcB.jpg\'}, {\'credit_id\': \'58ebe1fa925141281008e943\', \'department\': \'Production\', \'gender\': 2, \'id\': 58191, \'job\': \'Executive Producer\', \'name\': \'Chris Morgan\', \'profile_path\': \'/dUGxIwFBLrSFLImxjeda1krndMO.jpg\'}]'

In [11]:
eval(df[df['profit']==df['profit'].max()][['crew']].values[0][0])

[{'credit_id': '52fe4cc8c3a36847f823e681',
  'department': 'Production',
  'gender': 2,
  'id': 12835,
  'job': 'Producer',
  'name': 'Vin Diesel',
  'profile_path': '/7rwSXluNWZAluYMOEWBxkPmckES.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e687',
  'department': 'Production',
  'gender': 2,
  'id': 11874,
  'job': 'Producer',
  'name': 'Neal H. Moritz',
  'profile_path': '/cNcsEYmoS4niCz3UkVAA09dUIob.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e68d',
  'department': 'Writing',
  'gender': 2,
  'id': 58191,
  'job': 'Writer',
  'name': 'Chris Morgan',
  'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e693',
  'department': 'Writing',
  'gender': 0,
  'id': 8162,
  'job': 'Characters',
  'name': 'Gary Scott Thompson',
  'profile_path': '/e2dMfqFvRsOXgWZ1VToYLmos17y.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e699',
  'department': 'Directing',
  'gender': 2,
  'id': 2127,
  'job': 'Director',
  'name': 'James Wan',
  'profile_path': '/d1LSKfzi5J6QngWS7niN1zPJdud.jpg'},
 {'credit_id': '52fe4cc8c3a36847f823e6a7',
  'department': 'Camera',
  'gender': 2,
  'id': 58192,
  'job': 'Director of Photography',
  'name': 'Stephen F. Windon',
  'profile_path': None},
 {'credit_id': '5534714692514125dc002be4',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1455610,
  'job': 'Animation',
  'name': 'Tony Mecca',
  'profile_path': None},
 {'credit_id': '554fa7b992514110bd002a9d',
  'department': 'Camera',
  'gender': 0,
  'id': 1421687,
  'job': 'Director of Photography',
  'name': 'Marc Spicer',
  'profile_path': None},
 {'credit_id': '554fa7cbc3a36822540047fd',
  'department': 'Production',
  'gender': 1,
  'id': 90635,
  'job': 'Executive Producer',
  'name': 'Samantha Vincent',
  'profile_path': None},
 {'credit_id': '554fa7d89251413fcf00773d',
  'department': 'Production',
  'gender': 0,
  'id': 84064,
  'job': 'Associate Producer',
  'name': 'F. Valentino Morales',
  'profile_path': '/w85eCnNP0VgmfV5NWyq2SvRGi2y.jpg'},
 {'credit_id': '554fa7f2c3a3682254004803',
  'department': 'Production',
  'gender': 2,
  'id': 8181,
  'job': 'Producer',
  'name': 'Michael Fottrell',
  'profile_path': None},
 {'credit_id': '554fa80292514110bd002aa8',
  'department': 'Production',
  'gender': 0,
  'id': 75826,
  'job': 'Producer',
  'name': 'Brandon Birtell',
  'profile_path': None},
 {'credit_id': '55ed993ac3a3682c62015607',
  'department': 'Editing',
  'gender': 0,
  'id': 1204244,
  'job': 'Editor',
  'name': 'Leigh Folsom Boyd',
  'profile_path': None},
 {'credit_id': '55ed994cc3a3687d3b00d64c',
  'department': 'Editing',
  'gender': 0,
  'id': 1204245,
  'job': 'Editor',
  'name': 'Dylan Highsmith',
  'profile_path': None},
 {'credit_id': '55ed995dc3a3682c5d016867',
  'department': 'Editing',
  'gender': 0,
  'id': 62813,
  'job': 'Editor',
  'name': 'Kirk M. Morri',
  'profile_path': None},
 {'credit_id': '55ed99739251413e41014641',
  'department': 'Editing',
  'gender': 2,
  'id': 6668,
  'job': 'Editor',
  'name': 'Christian Wagner',
  'profile_path': None},
 {'credit_id': '55ed99859251413e3a014aae',
  'department': 'Production',
  'gender': 1,
  'id': 9545,
  'job': 'Casting',
  'name': 'Anne McCarthy',
  'profile_path': None},
 {'credit_id': '55ed99a4c3a3682c5d016875',
  'department': 'Production',
  'gender': 0,
  'id': 1276602,
  'job': 'Casting',
  'name': 'Kellie Roy',
  'profile_path': None},
 {'credit_id': '55ed99c7c3a3682c5d01687e',
  'department': 'Art',
  'gender': 0,
  'id': 1445830,
  'job': 'Art Direction',
  'name': 'Jonathan Carlos',
  'profile_path': None},
 {'credit_id': '55ed99d89251413e32014a65',
  'department': 'Art',
  'gender': 2,
  'id': 62780,
  'job': 'Art Direction',
  'name': 'Alan Hook',
  'profile_path': None},
 {'credit_id': '55ed99e992514106d600d85e',
  'department': 'Art',
  'gender': 0,
  'id': 1493864,
  'job': 'Art Direction',
  'name': 'Jay Pelissier',
  'profile_path': None},
 {'credit_id': '55ed9a36c3a3682c700147e3',
  'department': 'Art',
  'gender': 1,
  'id': 1506359,
  'job': 'Art Department Coordinator',
  'name': 'Kelly Richardson',
  'profile_path': None},
 {'credit_id': '55ed9a52c3a3682c640130c3',
  'department': 'Art',
  'gender': 0,
  'id': 1506360,
  'job': 'Art Department Coordinator',
  'name': 'Courtney Cocherell',
  'profile_path': None},
 {'credit_id': '55ed9a6cc3a368090c004f9c',
  'department': 'Art',
  'gender': 0,
  'id': 1326651,
  'job': 'Assistant Art Director',
  'name': 'Elena Albanese',
  'profile_path': None},
 {'credit_id': '55ed9a96c3a3686f17003be1',
  'department': 'Art',
  'gender': 0,
  'id': 1405376,
  'job': 'Assistant Art Director',
  'name': 'Alex McCarroll',
  'profile_path': None},
 {'credit_id': '55ed9acbc3a3682c640130e4',
  'department': 'Art',
  'gender': 0,
  'id': 1338147,
  'job': 'Construction Coordinator',
  'name': 'Bruce Di Valerio',
  'profile_path': None},
 {'credit_id': '55ed9b03c3a3682c640130f5',
  'department': 'Art',
  'gender': 2,
  'id': 52600,
  'job': 'Production Design',
  'name': 'Bill Brzeski',
  'profile_path': None},
 {'credit_id': '55ed9b169251413e2f0145a8',
  'department': 'Art',
  'gender': 1,
  'id': 75391,
  'job': 'Set Decoration',
  'name': 'Danielle Berman',
  'profile_path': None},
 {'credit_id': '55ed9b29c3a3682c5d0168d9',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 2519,
  'job': 'Costume Design',
  'name': 'Sanja Milkovic Hays',
  'profile_path': None},
 {'credit_id': '55ed9bdac3a3682c62015698',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1439109,
  'job': 'Costume Supervisor',
  'name': 'Nava R. Sadan',
  'profile_path': None},
 {'credit_id': '55ed9c0bc3a3686f17003c45',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1439747,
  'job': 'Costume Supervisor',
  'name': 'Andrew Hunt',
  'profile_path': None},
 {'credit_id': '55ed9c3192514106d600d8e0',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506364,
  'job': 'Set Costumer',
  'name': 'Jim Alan Cook',
  'profile_path': None},
 {'credit_id': '55ed9c45c3a3682c5d016925',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1415019,
  'job': 'Set Costumer',
  'name': 'Shayne Allen Duhon',
  'profile_path': None},
 {'credit_id': '55ed9c579251413e32014af5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506365,
  'job': 'Set Costumer',
  'name': 'Empress Holley',
  'profile_path': None},
 {'credit_id': '55ed9c6d9251413e450148ff',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1413125,
  'job': 'Set Costumer',
  'name': 'Marina Marit',
  'profile_path': None},
 {'credit_id': '55ed9c8d92514106d600d8fb',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506366,
  'job': 'Set Costumer',
  'name': 'Les Morgan',
  'profile_path': None},
 {'credit_id': '55ed9cda9251413e2f014612',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1408293,
  'job': 'Hairstylist',
  'name': 'Linda D. Flowers',
  'profile_path': None},
 {'credit_id': '55ed9cf69251413e2f01461d',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1412767,
  'job': 'Hairstylist',
  'name': "Yesim 'Shimmy' Osman",
  'profile_path': None},
 {'credit_id': '55ed9d0ec3a3687d3b00d73a',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506367,
  'job': 'Hairstylist',
  'name': 'Jennifer Santiago',
  'profile_path': None},
 {'credit_id': '55ed9d2a9251413e3e0155d8',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1425409,
  'job': 'Hairstylist',
  'name': 'Rachel Solow',
  'profile_path': None},
 {'credit_id': '55ed9d4cc3a3682c620156ed',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1452643,
  'job': 'Hairstylist',
  'name': 'Roxane Griffin',
  'profile_path': None},
 {'credit_id': '55ed9d6fc3a3682c5d01696f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1309209,
  'job': 'Makeup Department Head',
  'name': 'James MacKinnon',
  'profile_path': None},
 {'credit_id': '55ed9d8cc3a368090c00504f',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506368,
  'job': 'Makeup Artist',
  'name': 'Autumn Butler',
  'profile_path': None},
 {'credit_id': '55ed9da09251413e3a014b98',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1437798,
  'job': 'Makeup Artist',
  'name': "Roxy D'Alonzo",
  'profile_path': None},
 {'credit_id': '55ed9db79251413e3a014ba5',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1506369,
  'job': 'Makeup Artist',
  'name': 'Hee Soo Kwon',
  'profile_path': None},
 {'credit_id': '55ed9dce9251413e32014b4e',
  'department': 'Costume & Make-Up',
  'gender': 1,
  'id': 1459196,
  'job': 'Makeup Artist',
  'name': 'Sarah Mays',
  'profile_path': None},
 {'credit_id': '55ed9de4c3a3687d3b00d775',
  'department': 'Costume & Make-Up',
  'gender': 2,
  'id': 15330,
  'job': 'Makeup Artist',
  'name': 'Paul Pattison',
  'profile_path': None},
 {'credit_id': '55ed9df99251413e3e015610',
  'department': 'Costume & Make-Up',
  'gender': 0,
  'id': 1317667,
  'job': 'Makeup Artist',
  'name': 'Eleanor Sabaduquia',
  'profile_path': None},
 {'credit_id': '55ed9e1fc3a3687d3b00d77e',
  'department': 'Crew',
  'gender': 0,
  'id': 1414497,
  'job': 'Property Master',
  'name': 'Guillaume DeLouche',
  'profile_path': None},
 {'credit_id': '55ed9e3ac3a368090c005084',
  'department': 'Crew',
  'gender': 0,
  'id': 1464516,
  'job': 'Property Master',
  'name': 'Douglas T. Madison',
  'profile_path': None},
 {'credit_id': '55ed9f5d9251413e3e015662',
  'department': 'Crew',
  'gender': 2,
  'id': 57158,
  'job': 'Second Unit Cinematographer',
  'name': 'Igor Meglic',
  'profile_path': None},
 {'credit_id': '55ed9fa0c3a3682c6401320f',
  'department': 'Crew',
  'gender': 0,
  'id': 13670,
  'job': 'Second Unit Cinematographer',
  'name': 'Jacques Haitkin',
  'profile_path': None},
 {'credit_id': '55ed9fc59251413e32014bbc',
  'department': 'Lighting',
  'gender': 0,
  'id': 1437304,
  'job': 'Gaffer',
  'name': 'Michael Ambrose',
  'profile_path': None},
 {'credit_id': '55ed9fe79251413e410147e4',
  'department': 'Camera',
  'gender': 0,
  'id': 1506371,
  'job': 'Camera Operator',
  'name': 'Denise Bailie',
  'profile_path': None},
 {'credit_id': '55ed9ffa9251413e3a014c40',
  'department': 'Camera',
  'gender': 0,
  'id': 1506373,
  'job': 'Camera Operator',
  'name': 'Robert-James Bova',
  'profile_path': None},
 {'credit_id': '55eda0299251413e3a014c49',
  'department': 'Lighting',
  'gender': 0,
  'id': 1439108,
  'job': 'Rigging Gaffer',
  'name': 'Tom Fendley',
  'profile_path': None},
 {'credit_id': '55eda056c3a3682c7001494b',
  'department': 'Camera',
  'gender': 0,
  'id': 1434896,
  'job': 'Camera Operator',
  'name': 'Sarah Levy',
  'profile_path': None},
 {'credit_id': '55eda06e9251413e450149ee',
  'department': 'Camera',
  'gender': 2,
  'id': 74989,
  'job': 'Camera Operator',
  'name': 'Mark Emery Moore',
  'profile_path': '/mhjX0FuAXv6SeSLLFHpaaiQbx6P.jpg'},
 {'credit_id': '55eda082c3a3682c6b014009',
  'department': 'Camera',
  'gender': 2,
  'id': 1432918,
  'job': 'Camera Operator',
  'name': 'Daniel Nichols',
  'profile_path': None},
 {'credit_id': '55eda09d9251413e3e01569d',
  'department': 'Camera',
  'gender': 0,
  'id': 1439104,
  'job': 'Camera Operator',
  'name': 'Onofrio Nino Pansini',
  'profile_path': None},
 {'credit_id': '55eda0b59251413e3a014c6c',
  'department': 'Camera',
  'gender': 0,
  'id': 1408356,
  'job': 'Camera Operator',
  'name': 'David Richert',
  'profile_path': None},
 {'credit_id': '55eda0d1c3a3686f17003d58',
  'department': 'Camera',
  'gender': 2,
  'id': 1411271,
  'job': 'Camera Operator',
  'name': 'Michael J. Walker',
  'profile_path': None},
 {'credit_id': '55eda0f7c3a3687d3b00d81b',
  'department': 'Camera',
  'gender': 2,
  'id': 1378241,
  'job': 'Camera Operator',
  'name': 'Maurice K. McGuire',
  'profile_path': None},
 {'credit_id': '55eda1159251413e3e0156bd',
  'department': 'Camera',
  'gender': 0,
  'id': 1411842,
  'job': 'Camera Operator',
  'name': 'Richard Latham',
  'profile_path': None},
 {'credit_id': '55eda12c92514106d600da0a',
  'department': 'Camera',
  'gender': 0,
  'id': 1404739,
  'job': 'Helicopter Camera',
  'name': 'Steve Koster',
  'profile_path': None},
 {'credit_id': '55eda1939251413e3501498d',
  'department': 'Camera',
  'gender': 0,
  'id': 91122,
  'job': 'Helicopter Camera',
  'name': 'Dylan Goss',
  'profile_path': None},
 {'credit_id': '55eda1b39251413e3a014ca8',
  'department': 'Camera',
  'gender': 0,
  'id': 82169,
  'job': 'Steadicam Operator',
  'name': 'Geoffrey Haley',
  'profile_path': None},
 {'credit_id': '55eda1c7c3a3686f17003d8c',
  'department': 'Camera',
  'gender': 0,
  'id': 1419105,
  'job': 'Still Photographer',
  'name': 'Scott Garfield',
  'profile_path': None},
 {'credit_id': '55eda1dbc3a3686f17003d92',
  'department': 'Camera',
  'gender': 2,
  'id': 1395281,
  'job': 'Additional Camera',
  'name': 'Bob Gorelick',
  'profile_path': None},
 {'credit_id': '55eda200c3a3682c5d016a8f',
  'department': 'Camera',
  'gender': 0,
  'id': 1375920,
  'job': 'Additional Camera',
  'name': 'J. Christopher Campbell',
  'profile_path': None},
 {'credit_id': '55eda228c3a3682c64013295',
  'department': 'Lighting',
  'gender': 0,
  'id': 1403412,
  'job': 'Gaffer',
  'name': 'Dan Cornwall',
  'profile_path': None},
 {'credit_id': '55eda25f92514106d600da4b',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1442137,
  'job': 'Animation Supervisor',
  'name': 'Catherine Mullan',
  'profile_path': None},
 {'credit_id': '55eda292c3a3682c5d016ab2',
  'department': 'Sound',
  'gender': 0,
  'id': 1393405,
  'job': 'Music Editor',
  'name': 'Robb Boyd',
  'profile_path': None},
 {'credit_id': '55eda2a9c3a3682c6b014075',
  'department': 'Sound',
  'gender': 0,
  'id': 1328758,
  'job': 'Music Editor',
  'name': 'Matthew Llewellyn',
  'profile_path': None},
 {'credit_id': '55eda2c89251413e45014a6d',
  'department': 'Directing',
  'gender': 0,
  'id': 1389138,
  'job': 'Script Supervisor',
  'name': 'Jody Blose',
  'profile_path': None},
 {'credit_id': '55eda305c3a3682c700149c1',
  'department': 'Directing',
  'gender': 0,
  'id': 1408365,
  'job': 'Script Supervisor',
  'name': 'Brenda K. Wachel',
  'profile_path': None},
 {'credit_id': '55eda32dc3a3686f17003ddd',
  'department': 'Crew',
  'gender': 2,
  'id': 8167,
  'job': 'Thanks',
  'name': 'Paul Walker',
  'profile_path': '/iqvYezRoEY5k8wnlfHriHQfl5dX.jpg'},
 {'credit_id': '55eda3b592514106d600da94',
  'department': 'Editing',
  'gender': 0,
  'id': 1400354,
  'job': 'Digital Intermediate',
  'name': 'Amy Pawlowski',
  'profile_path': None},
 {'credit_id': '55eda3d792514106d600da9b',
  'department': 'Editing',
  'gender': 0,
  'id': 110262,
  'job': 'First Assistant Editor',
  'name': 'Richard Conkling',
  'profile_path': None},
 {'credit_id': '55eda3edc3a3686f17003e0c',
  'department': 'Editing',
  'gender': 0,
  'id': 1194885,
  'job': 'First Assistant Editor',
  'name': 'Dave  Cory',
  'profile_path': None},
 {'credit_id': '55eda4169251413e410148ec',
  'department': 'Editing',
  'gender': 0,
  'id': 1439749,
  'job': 'First Assistant Editor',
  'name': 'Laura Steiger',
  'profile_path': None},
 {'credit_id': '55eda48092514106d600daba',
  'department': 'Visual Effects',
  'gender': 0,
  'id': 1506377,
  'job': 'Animation Supervisor',
  'name': 'Daniel Barrett',
  'profile_path': '/pplTJP3gCWmP3SMDrXjOt1579MV.jpg'},
 {'credit_id': '55eda5109251413e32014cf0',
  'department': 'Sound',
  'gender': 0,
  'id': 12562,
  'job': 'ADR & Dubbing',
  'name': 'Anna MacKenzie',
  'profile_path': None},
 {'credit_id': '55eda51ac3a3686f17003e52',
  'department': 'Editing',
  'gender': 0,
  'id': 12562,
  'job': 'Dialogue Editor',
  'name': 'Anna MacKenzie',
  'profile_path': None},
 {'credit_id': '55eda539c3a368090c0051c2',
  'department': 'Editing',
  'gender': 0,
  'id': 1342658,
  'job': 'Dialogue Editor',
  'name': 'Frederick H. Stahly',
  'profile_path': None},
 {'credit_id': '55eda56a9251413e45014adf',
  'department': 'Sound',
  'gender': 2,
  'id': 1077782,
  'job': 'Foley',
  'name': 'Gary A. Hecker',
  'profile_path': '/qyBUauN3XIS2Mlus3OdGCmrUo0S.jpg'},
 {'credit_id': '55eda58292514106d600daf4',
  'department': 'Sound',
  'gender': 0,
  'id': 1367362,
  'job': 'Foley',
  'name': 'Rick Owens',
  'profile_path': None},
 {'credit_id': '55eda59ac3a3682c5d016b50',
  'department': 'Sound',
  'gender': 0,
  'id': 1236340,
  'job': 'Foley',
  'name': 'Dylan Tuomy-Wilhoit',
  'profile_path': None},
 {'credit_id': '55eda5b09251413e45014af1',
  'department': 'Sound',
  'gender': 0,
  'id': 548445,
  'job': 'Foley',
  'name': 'Jeffrey Wilhoit',
  'profile_path': None},
 {'credit_id': '55eda7169251413e45014b3b',
  'department': 'Sound',
  'gender': 2,
  'id': 7239,
  'job': 'Sound Designer',
  'name': 'Peter Brown',
  'profile_path': None},
 {'credit_id': '55eda73d9251413e4101498c',
  'department': 'Sound',
  'gender': 0,
  'id': 1392083,
  'job': 'Sound Designer',
  'name': 'Ann Scibelli',
  'profile_path': None},
 {'credit_id': '55eda779c3a3682c70014abc',
  'department': 'Sound',
  'gender': 0,
  'id': 1413453,
  'job': 'Sound Effects Editor',
  'name': 'Stephen P. Robinson',
  'profile_path': None},
 {'credit_id': '55eda7989251413e3e015838',
  'department': 'Sound',
  'gender': 0,
  'id': 1394131,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Jon Taylor',
  'profile_path': None},
 {'credit_id': '55eda7afc3a3686f17003ebf',
  'department': 'Sound',
  'gender': 0,
  'id': 1394130,
  'job': 'Sound Re-Recording Mixer',
  'name': 'Frank A. Monta√±o',
  'profile_path': None},
 {'credit_id': '55eda7d79251413e32014e11',
  'department': 'Sound',
  'gender': 0,
  'id': 1309884,
  'job': 'Supervising Sound Editor',
  'name': 'Joe Dzuban',
  'profile_path': None},
 {'credit_id': '570bd40dc3a36802a30002d9',
  'department': 'Art',
  'gender': 0,
  'id': 1424153,
  'job': 'Supervising Art Director',
  'name': 'Desma Murphy',
  'profile_path': None},
 {'credit_id': '5668cc7a92514174040040f2',
  'department': 'Sound',
  'gender': 2,
  'id': 6041,
  'job': 'Original Music Composer',
  'name': 'Brian Tyler',
  'profile_path': '/22QWiNJj03amY6GT1QPUs7dbdcB.jpg'},
 {'credit_id': '58ebe1fa925141281008e943',
  'department': 'Production',
  'gender': 2,
  'id': 58191,
  'job': 'Executive Producer',
  'name': 'Chris Morgan',
  'profile_path': '/dUGxIwFBLrSFLImxjeda1krndMO.jpg'}]

In [12]:
for i in eval(df[df['profit']==df['profit'].max()][['crew']].values[0][0]):
  print(i['name'],'->',i['job'])

Vin Diesel -> Producer
Neal H. Moritz -> Producer
Chris Morgan -> Writer
Gary Scott Thompson -> Characters
James Wan -> Director
Stephen F. Windon -> Director of Photography
Tony Mecca -> Animation
Marc Spicer -> Director of Photography
Samantha Vincent -> Executive Producer
F. Valentino Morales -> Associate Producer
Michael Fottrell -> Producer
Brandon Birtell -> Producer
Leigh Folsom Boyd -> Editor
Dylan Highsmith -> Editor
Kirk M. Morri -> Editor
Christian Wagner -> Editor
Anne McCarthy -> Casting
Kellie Roy -> Casting
Jonathan Carlos -> Art Direction
Alan Hook -> Art Direction
Jay Pelissier -> Art Direction
Kelly Richardson -> Art Department Coordinator
Courtney Cocherell -> Art Department Coordinator
Elena Albanese -> Assistant Art Director
Alex McCarroll -> Assistant Art Director
Bruce Di Valerio -> Construction Coordinator
Bill Brzeski -> Production Design
Danielle Berman -> Set Decoration
Sanja Milkovic Hays -> Costume Design
Nava R. Sadan -> Costume Supervisor
Andrew Hunt -> Costume Supervisor
Jim Alan Cook -> Set Costumer
Shayne Allen Duhon -> Set Costumer
Empress Holley -> Set Costumer
Marina Marit -> Set Costumer
Les Morgan -> Set Costumer
Linda D. Flowers -> Hairstylist
Yesim 'Shimmy' Osman -> Hairstylist
Jennifer Santiago -> Hairstylist
Rachel Solow -> Hairstylist
Roxane Griffin -> Hairstylist
James MacKinnon -> Makeup Department Head
Autumn Butler -> Makeup Artist
Roxy D'Alonzo -> Makeup Artist
Hee Soo Kwon -> Makeup Artist
Sarah Mays -> Makeup Artist
Paul Pattison -> Makeup Artist
Eleanor Sabaduquia -> Makeup Artist
Guillaume DeLouche -> Property Master
Douglas T. Madison -> Property Master
Igor Meglic -> Second Unit Cinematographer
Jacques Haitkin -> Second Unit Cinematographer
Michael Ambrose -> Gaffer
Denise Bailie -> Camera Operator
Robert-James Bova -> Camera Operator
Tom Fendley -> Rigging Gaffer
Sarah Levy -> Camera Operator
Mark Emery Moore -> Camera Operator
Daniel Nichols -> Camera Operator
Onofrio Nino Pansini -> Camera Operator
David Richert -> Camera Operator
Michael J. Walker -> Camera Operator
Maurice K. McGuire -> Camera Operator
Richard Latham -> Camera Operator
Steve Koster -> Helicopter Camera
Dylan Goss -> Helicopter Camera
Geoffrey Haley -> Steadicam Operator
Scott Garfield -> Still Photographer
Bob Gorelick -> Additional Camera
J. Christopher Campbell -> Additional Camera
Dan Cornwall -> Gaffer
Catherine Mullan -> Animation Supervisor
Robb Boyd -> Music Editor
Matthew Llewellyn -> Music Editor
Jody Blose -> Script Supervisor
Brenda K. Wachel -> Script Supervisor
Paul Walker -> Thanks
Amy Pawlowski -> Digital Intermediate
Richard Conkling -> First Assistant Editor
Dave  Cory -> First Assistant Editor
Laura Steiger -> First Assistant Editor
Daniel Barrett -> Animation Supervisor
Anna MacKenzie -> ADR & Dubbing
Anna MacKenzie -> Dialogue Editor
Frederick H. Stahly -> Dialogue Editor
Gary A. Hecker -> Foley
Rick Owens -> Foley
Dylan Tuomy-Wilhoit -> Foley
Jeffrey Wilhoit -> Foley
Peter Brown -> Sound Designer
Ann Scibelli -> Sound Designer
Stephen P. Robinson -> Sound Effects Editor
Jon Taylor -> Sound Re-Recording Mixer
Frank A. Monta√±o -> Sound Re-Recording Mixer
Joe Dzuban -> Supervising Sound Editor
Desma Murphy -> Supervising Art Director
Brian Tyler -> Original Music Composer
Chris Morgan -> Executive Producer

In [13]:
for i in eval(df[df['profit']==df['profit'].max()][['crew']].values[0][0]):
  if i['job']=='Producer':
   print(i['name'])

print("Director Name-")
for i in eval(df[df['profit']==df['profit'].max()][['crew']].values[0][0]):
  if i['job']=='Director':
   print(i['name'])

Vin Diesel
Neal H. Moritz
Michael Fottrell
Brandon Birtell
Director Name-
James Wan

**1. Which movie made the highest profit? Who were its producer and director? Identify the actors in that film.**

In [14]:
# Method one.
actor_list=[]
for i in eval(df[df['profit']==df['profit'].max()][['cast']].values[0][0]):
  actor_list.append(i['name'])

print(actor_list)

['Vin Diesel', 'Paul Walker', 'Dwayne Johnson', 'Michelle Rodriguez', 'Tyrese Gibson', 'Ludacris', 'Jordana Brewster', 'Djimon Hounsou', 'Tony Jaa', 'Ronda Rousey', 'Nathalie Emmanuel', 'Kurt Russell', 'Jason Statham', 'Sung Kang', 'Gal Gadot', 'Lucas Black', 'Elsa Pataky', 'Noel Gugliemi', 'John Brotherton', 'Luke Evans', 'Ali Fazal', 'Miller Kimsey', 'Charlie Kimsey', 'Eden Estrella', 'Gentry White', 'Iggy Azalea', 'Jon Lee Brody', 'Levy Tran', 'Anna Colwell', 'Viktor Hernandez', 'Steve Coulter', 'Robert Pralgo', 'Antwan Mills', 'J.J. Phillips', 'Jorge Ferragut', 'Sara Sohn', 'Benjamin Blankenship', 'D.J. Hapa', 'T-Pain', 'Brian Mahoney', 'Brittney Alger', 'Romeo Santos', 'Jocelin Donahue', 'Stephanie Langston', 'Jorge-Luis Pallo', 'Tego Calder√≥n', 'Nathalie Kelley', 'Shad Moss', 'Don Omar', 'Klement Tinaj', 'Caleb Walker', 'Cody Walker']

In [15]:
# Method two
actor_list1=[]
for i in df[df['profit']==df['profit'].max()]['cast']:
  for j in eval(i):
    actor_list1.append(j['name'])


print(actor_list1)

['Vin Diesel', 'Paul Walker', 'Dwayne Johnson', 'Michelle Rodriguez', 'Tyrese Gibson', 'Ludacris', 'Jordana Brewster', 'Djimon Hounsou', 'Tony Jaa', 'Ronda Rousey', 'Nathalie Emmanuel', 'Kurt Russell', 'Jason Statham', 'Sung Kang', 'Gal Gadot', 'Lucas Black', 'Elsa Pataky', 'Noel Gugliemi', 'John Brotherton', 'Luke Evans', 'Ali Fazal', 'Miller Kimsey', 'Charlie Kimsey', 'Eden Estrella', 'Gentry White', 'Iggy Azalea', 'Jon Lee Brody', 'Levy Tran', 'Anna Colwell', 'Viktor Hernandez', 'Steve Coulter', 'Robert Pralgo', 'Antwan Mills', 'J.J. Phillips', 'Jorge Ferragut', 'Sara Sohn', 'Benjamin Blankenship', 'D.J. Hapa', 'T-Pain', 'Brian Mahoney', 'Brittney Alger', 'Romeo Santos', 'Jocelin Donahue', 'Stephanie Langston', 'Jorge-Luis Pallo', 'Tego Calder√≥n', 'Nathalie Kelley', 'Shad Moss', 'Don Omar', 'Klement Tinaj', 'Caleb Walker', 'Cody Walker']

In [16]:
#Director
director=[]
for i in eval(df[df['profit']==df['profit'].max()][['crew']].values[0][0]):
  if i['job']=='Director':
    director.append(i['name'])

print(director)

['James Wan']

In [17]:
#Producer
Producer=[]
for i in eval(df[df['profit']==df['profit'].max()][['crew']].values[0][0]):
  if i['job']=='Producer':
    Producer.append(i['name'])

print(Producer)

['Vin Diesel', 'Neal H. Moritz', 'Michael Fottrell', 'Brandon Birtell']

2.This data has information about movies made in different languages. Which language has the highest average ROI (return on investment)?

In [18]:
df['ROI']=100*df['profit']/df['budget']
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,ROI
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,-12.038207
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,137.873588
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,296.727273
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,1233.333333
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,3923970,inf

In [19]:
df.groupby(['original_language'])['ROI'].mean()

original_language
ar            inf
bn            inf
cn            inf
cs            inf
da            inf
de            inf
el    5198.013245
en            inf
es            inf
fa            inf
fi     -30.319235
fr            inf
he     456.292450
hi            inf
hu            inf
id     -41.617578
it            inf
ja            inf
ko            inf
ml     370.833333
mr     193.333333
nb      18.847943
nl            inf
no            inf
pl     395.816987
pt            inf
ro            inf
ru            inf
sr     -99.960400
sv            inf
ta            inf
te     440.076812
tr            inf
ur     350.673773
vi     -50.846154
zh            inf
Name: ROI, dtype: float64

In [20]:
df.describe()

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:4779: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,id,budget,popularity,runtime,revenue,profit,ROI
count,3000.000000,3.000000e+03,3000.000000,2998.000000,3.000000e+03,3.000000e+03,3000.000000
mean,1500.500000,2.253133e+07,8.463274,107.856571,6.672585e+07,4.419452e+07,inf
std,866.169729,3.702609e+07,12.104000,22.086434,1.375323e+08,1.123274e+08,NaN
min,1.000000,0.000000e+00,0.000001,0.000000,1.000000e+00,-1.074474e+08,-99.999948
25%,750.750000,0.000000e+00,4.018053,94.000000,2.379808e+06,1.795200e+04,17.176318
50%,1500.500000,8.000000e+06,7.374861,104.000000,1.680707e+07,6.121122e+06,239.984076
75%,2250.250000,2.900000e+07,10.890983,118.000000,6.891920e+07,4.143293e+07,NaN
max,3000.000000,3.800000e+08,294.337037,338.000000,1.519558e+09,1.316249e+09,inf

In [21]:
df['revenue'].median()

16807068.0

In [22]:
df['budget'].median()

8000000.0

In [23]:
df.loc[df['revenue']<1000,'revenue']=df['revenue'].median()

In [24]:
df.loc[df['budget']<1000,'budget']=df['budget'].median()

In [25]:
df.describe()

/usr/local/lib/python3.12/dist-packages/numpy/lib/_function_base_impl.py:4779: RuntimeWarning: invalid value encountered in subtract
  diff_b_a = subtract(b, a)

,id,budget,popularity,runtime,revenue,profit,ROI
count,3000.000000,3.000000e+03,3000.000000,2998.000000,3.000000e+03,3.000000e+03,3000.000000
mean,1500.500000,2.474467e+07,8.463274,107.856571,6.704518e+07,4.419452e+07,inf
std,866.169729,3.583254e+07,12.104000,22.086434,1.373964e+08,1.123274e+08,NaN
min,1.000000,2.500000e+03,0.000001,0.000000,1.404000e+03,-1.074474e+08,-99.999948
25%,750.750000,8.000000e+06,4.018053,94.000000,2.947600e+06,1.795200e+04,17.176318
50%,1500.500000,8.000000e+06,7.374861,104.000000,1.680873e+07,6.121122e+06,239.984076
75%,2250.250000,2.900000e+07,10.890983,118.000000,6.891920e+07,4.143293e+07,NaN
max,3000.000000,3.800000e+08,294.337037,338.000000,1.519558e+09,1.316249e+09,inf

In [26]:
df['profit'] = df['revenue']-df['budget']

In [27]:
df.head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,ROI
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,-12.038207
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,137.873588
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,296.727273
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,1233.333333
4,5,NaN,8000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,-4076030,inf
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638,-4738362,-59.229525
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075,71446075,510.329107
7,8,NaN,8000000,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511,-5413489,inf
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",8000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Set sail for Muppet mayhem!,Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391,26327391,inf
9,10,NaN,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,tt0310281,en,A Mighty Wind,"In ""A Mighty Wind"", director Christopher Guest...",4.672036,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Back together for the first time, again.",A Mighty Wind,"[{'id': 11800, 'name': 'mockumentary'}, {'id':...","[{'cast_id': 24, 'character': 'Jonathan Steinb...","[{'credit_id': '52fe45609251416c750545b3', 'de...",18750246,12750246,212.504100

In [28]:
df['ROI']=100*df['profit']/df['budget']
df.head(10)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,profit,ROI
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,-1685349,-12.038207
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,55149435,137.873588
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,9792000,296.727273
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,14800000,1233.333333
4,5,NaN,8000000,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,-4076030,-50.950375
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638,-4738362,-59.229525
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075,71446075,510.329107
7,8,NaN,8000000,"[{'id': 99, 'name': 'Documentary'}]",NaN,tt0391024,en,Control Room,A chronicle which provides a rare window into ...,1.949044,...,"[{'iso_639_1': 'ar', 'name': 'العربية'}, {'iso...",Released,Different channels. Different truths.,Control Room,"[{'id': 917, 'name': 'journalism'}, {'id': 163...","[{'cast_id': 2, 'character': 'Himself', 'credi...","[{'credit_id': '52fe47a69251416c750a0daf', 'de...",2586511,-5413489,-67.668612
8,9,"[{'id': 256377, 'name': 'The Muppet Collection...",8000000,"[{'id': 28, 'name': 'Action'}, {'id': 35, 'nam...",NaN,tt0117110,en,Muppet Treasure Island,After telling the story of Flint's last journe...,6.902423,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Set sail for Muppet mayhem!,Muppet Treasure Island,"[{'id': 2041, 'name': 'island'}, {'id': 4418, ...","[{'cast_id': 1, 'character': 'Long John Silver...","[{'credit_id': '52fe43c89251416c7501deb3', 'de...",34327391,26327391,329.092387
9,10,NaN,6000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10402, '...",NaN,tt0310281,en,A Mighty Wind,"In ""A Mighty Wind"", director Christopher Guest...",4.672036,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,"Back together for the first time, again.",A Mighty Wind,"[{'id': 11800, 'name': 'mockumentary'}, {'id':...","[{'cast_id': 24, 'character': 'Jonathan Steinb...","[{'credit_id': '52fe45609251416c750545b3', 'de...",18750246,12750246,212.504100

In [29]:
df.groupby(['original_language'])['ROI'].mean().sort_values(ascending=False).head(10)

original_language
ko    11309.685605
el     5198.013245
sr     3261.413600
en      952.119148
tr      878.917604
de      550.245452
he      456.292450
te      440.076812
pl      395.816987
ml      370.833333
Name: ROI, dtype: float64

3.Find out the unique genres of movies in this dataset?

In [30]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'profit', 'ROI'],
      dtype='object')

In [31]:
df['genres'].isnull().sum()

np.int64(7)

In [32]:
not_null_genres=df[~df['genres'].isna()]
not_null_genres['genres'].isnull().sum()

np.int64(0)

In [33]:
#In this method this is dome by removing all the null values
genres_list=[]
for i in not_null_genres['genres'][:]:
  for j in eval(i):
    genres_list.append(j['name'])


print(set(genres_list))

{'Crime', 'Comedy', 'Documentary', 'Action', 'Western', 'Science Fiction', 'Mystery', 'Fantasy', 'Thriller', 'Romance', 'Horror', 'Foreign', 'TV Movie', 'War', 'Family', 'Drama', 'Adventure', 'Animation', 'Music', 'History'}

In [34]:
genres_list1=[]
try:
  for i in df['genres'][:]:
    for j in eval(i):
      genres_list1.append(j['name'])

except:
  pass

print(set(genres_list1))

{'Crime', 'Comedy', 'Documentary', 'Action', 'Western', 'Science Fiction', 'Mystery', 'Fantasy', 'Thriller', 'Romance', 'Horror', 'Foreign', 'War', 'Family', 'Drama', 'Adventure', 'Animation', 'Music', 'History'}

4.Which actor has acted in the most number of movies? Deep dive into the movies, genres and profits corresponding to this actor?

In [35]:
movie_actor=[]

try:
  for i in df['cast'][:]:
    for j in eval(i):
      movie_actor.append(j['name'])

except:
  pass

print(set(movie_actor))

{'Michael Laauli Hayner', 'Jimmy Lin', 'Fiona Glascott', 'Miyavi', 'Alex Wolff', 'David Sterne', 'Liza Weil', 'Eriq La Salle', 'Ed Anders', 'Courtney Tailor', 'Jonathan Wilson', 'Nicholas Bell', 'Mari Jaramillo', 'Tommy Davidson', 'Caitlin Rose Anderson', 'Henry Kelemen', 'Lottie Hamilton', 'Veit St√ºbner', 'Antoine Laurent', 'Philip Barantini', 'Alina Babak', 'Rick Irwin', 'Taka Uematsu', 'Brad William Henke', 'Cress Williams', 'Paul Bettany', 'Phil Leeds', 'Fred Ward', 'Adam Storke', 'Vsevolod Tsurilo', 'Brenda Fricker', 'Danny Bonaduce', 'Maxwell Perry Cotton', 'Stephen Shellen', 'Divya Satia', 'Michele Brilliant', 'Kenneth Tobey', 'Andrew Blanchard', 'Robert Townsend', 'Andr√© Hennicke', 'Jeanne Bates', 'Jane Seymour', 'Don McManus', 'Drew Sawyer', 'Diane-Louise Jordan', 'Luis Callejo', 'Joshua Wolf Coleman', 'Diane Hartford', 'Big John', 'Igal Naor', 'Daniel Pr√©vost', 'Roy C. Peterson', 'Henry Wilcoxon', 'David McConnell', 'Darcy Higginbotham', 'Minae Noji', 'Marta Kristen', 'Crystal Anne Dickinson', 'Debbee Hinchcliffe', 'Orlando Bloom', 'Chris Mulkey', 'Thomas Morrison', 'Dragan Miƒáanoviƒá', 'Aidan Quinn', 'Robert Webber', 'Robert Knepper', 'Pierre Palmade', 'Sylvia Lewis', 'Gary Carlos Cervantes', 'Beatrice Rosen', 'Michael Sheets', 'Sumithra', 'Valentina Forte', 'Doug Roberts', 'Michael Anderson Jr.', 'Jon Ted Wynne', 'Tom Berenger', 'Jamie Bell', 'Anna Maria Horsford', 'Guy Pearce', 'Katherine Helmond', 'David Huband', 'Margo Martindale', 'Irrfan Khan', "Robert Z'Dar", 'Xavier Robic', 'George Georgiou', 'Wanni-Omni-Ska-Robideau', 'Ralph Macchio', 'Martina Duravol√°', 'Brian Libby', 'Rob Steinberg', 'Victor Spinetti', 'Eddie Jones', 'Kevin Nealon', 'David Rasche', 'Sunny Sandler', 'Patrice Rohmer', 'Lavelle Roby', 'Sharon Lawrence', 'Humpy Wheeler', 'Iddo Goldberg', 'Dean Mumford', 'Kevin Costner', 'Parry Shen', 'Ed Ackerman', 'Teresa Pavlinek', 'Tracy McMahon', 'Aaron Berg', 'Gerry May', 'Bradley Cooper', 'Steven Gilborn', 'George Tchortov', 'Nicolette Krebitz', 'Maxine Peake', 'Alakina Mann', 'Michael Halton', 'Brian Mahoney', 'Angela Lanza', 'Paulene Myers', 'Carl Mazzocone Sr.', 'Richard Pilcher', 'Jalina Mercado', 'Anita Daher', 'Mark Bringelson', 'Sophie Faucher', 'Maurizio Romoli', 'Jennifer Balgobin', 'Abbie Dunn', 'Laura Williams', 'Ross Anderson', 'Christopher Lee', 'Kevin McNulty', 'Gina Gershon', 'Peter Falk', 'Saswata Chatterjee', 'Bob Bragg', 'Donald Bostr√∂m', 'Philip Chan Yan-Kin', 'John Innes', 'Enrique Lucero', 'Vivian Vance', 'Conchita Montes', 'Absa Diatou Toure', 'James Sikking', 'Don Johnson', 'Tessa Ludwick', 'George Kennedy', 'Dean Lopata', 'Colin Carnegie', 'John Schnauder Jr.', 'Ian Eastwood', 'Yoji Tatsuta', 'Will Barton', 'Erik Cord', 'Julija Steponaitytƒó', 'David Evanson', 'Cary-Hiroyuki Tagawa', 'Tony Nappo', 'Carlo Cecchi', 'Keram Malicki-S√°nchez', 'Vyacheslav Razbegaev', 'Howard Duff', 'Michel Winogradoff', 'Bill McCallum', 'Richard James', 'John Burke', 'E. Kalani Flores', 'Carol Channing', 'Tim J. Smith', 'Ingrid Vold', 'Bobby Harwell', 'Hassan Johnson', 'Blake Lindsley', 'Robert Bathurst', 'Douglas McFerran', 'Goldie Hawn', 'Cynthia Dale Scott', 'David C. Fisher', 'Bryan Connolly', 'James Robinson', 'Nancy Marshall', 'Dale Gibson', 'Alice Orr-Ewing', 'Katarzyna Wolejnio', 'Peter Geeves', 'Rosalind Feldman', 'Paige Coffman', 'Jimmy Hayward', 'Guy Oliver-Watts', 'Kyra Sedgwick', 'Amber Heard', 'Louis Charles Mounicou III', 'Stink Fisher', 'Ted Koppel', 'Daniel Wu', 'Linds Edwards', 'Maile Flanagan', 'Lewis Hamilton', 'Seth Gilliam', 'Larry Drake', 'Sm√°ri McCarthy', 'Wendee Lee', 'Audrey Hepburn', 'Abigail Breslin', 'Clyde Kusatsu', 'William Scott-Masson', 'Roger Cross', 'Vladimir Alexis', 'Chris Spencer', 'S√∂ren Rochefort', 'Helena Bereen', 'Fred Tatasciore', 'Rosie Perez', "Patrick O'Hara", 'David Hemblen', 'Brian Markinson', 'Nina Dobrev', 'Robyn Reede', 'Stuart Yee', 'Alessandra Negrini', 'Sophie Perry', 'Victoria Emslie', 'Hallee Hirsh', 'Ben Mendelsohn', 'Rebecca Drysdale', 'David J. Lyle', 'Jason Bynum', 'Willie Col√≥n', 'Will Patton', 'Seiji Rokkaku', 'Liam Hemsworth', 'Kyle Gatehouse', 'Javier Bardem', 'Harris Yulin', 'Tsuyoshi Ihara', 'Alessandro Gassman', 'Kendra C. Johnson', 'Tim Trella', 'Mildred Dunnock', 'Claire Danes', 'Fat Joe', 'Jordi Moll√†', 'Julie Delpy', 'Kim Basinger', 'Tyler Coppin', 'Freddy Bosche', 'Wilfred E. Williams', 'Angel Garnica', 'Oakley Lehman', 'Brian Lonsdale', 'Brigid Berlin', 'Keenen Ivory Wayans', 'Don Stroud', 'Amy Ryan', 'Daniel Massey', 'Hank Azaria', "Maureen O'Hara", 'Ryan Malgarini', 'Damon Wayans', 'Cory Bowles', 'Sid Haig', 'Jakob Davies', 'Will Rothhaar', 'Kevin Thigpen', 'Pierre Alloggia', 'Luiz Armando Queiroz', 'Nicole Kidman', 'Danny Huston', 'Rinko Kikuchi', 'Gr√©goire Oestermann', 'Marion Reymond', 'Chris Bearne', 'Gertrude Michael', 'Russell Edge', 'Devin Sidell', 'Ben Presley', 'John Daniel', 'Bryan Callen', 'Adam Waxman', 'Stephen E. Miller', 'Sitaram Panchal', 'Alan Polonsky', 'Hunter McGilvray', 'Eric MacLennan', 'Gemma Jones', 'Paula Francis', 'Lou Antonio', 'Craig T. Nelson', 'David Carradine', 'Marcus Graham', 'Malcolm Atterbury', 'Gia Carides', 'Richard Jenkins', 'Ashley Crow', 'James Ashcroft', "William 'Buddy' Byrd", 'Brenda Eimers', 'Brian Blain', 'Chi McBride', 'Justin Henry', 'Zelmar Gue√±ol', 'Urbano Barberini', 'Jon Briddell', 'Federica Cassini', 'Peter Feeney', 'Steve White', 'Seymour Cassel', 'William Jordan', 'Rocco Sisto', 'Victor Sobchak', 'Jeremy Fitzgerald', 'Nancy Bach', 'Heather Hach', 'Jeanette Kontomitras', 'Joanna Pacula', 'Ted Nobriga', 'Lily Knight', 'Jamie Moore', 'Chris Matheny', 'Mitch Pileggi', 'Chuck Pacheco', 'Lauren Bacall', 'Walt La Rue', 'Dominique Pozzetto', 'Tobey Maguire', 'Trent McMullen', 'Michael Rispoli', 'Roy Jenson', "Robert 'Toshi' Kar Yuen Chan", 'Bruce McLaughlin', 'Scott E. Miller', 'Chris Parnell', 'Kim Teboul', 'Will Smith', 'Azhagam Perumal', 'Ulrich Matthes', 'Ben Shenkman', 'Ekrem Aral Tuna', "Michael O'Keefe", 'Matt Levett', 'David St. James', 'Angel Coulby', 'Nicholas Celozzi', 'Murray Gershenz', 'Nancy Fish', 'Angela Pleasence', 'Kristoffer Greaves', 'Lawrence B. Adisa', 'Kris Kristofferson', 'Luis Felipe Tovar', 'Karyn Beach', 'Lauren Weedman', 'Omar Sharif', 'Kirk Jones', 'Courtney Ford', 'Billy Ray Cyrus', 'Roger Moore', 'Andrew Lowery', 'Richard Brake', 'Sammy Davis, Jr.', 'Jesse Hernandez', 'Daniel Rashev', 'Joe Kaplan', 'Caitlin Carmichael', 'Holland Taylor', 'Gene Barry', 'Jamie Beamish', 'Antonio Catania', 'Ann Dowd', 'Quinn Lord', 'Martin Campbell', 'Alphonse Martell', 'Tony Curtis', 'Kim Joon-bae', 'Julie Manase', 'Bentley Mitchum', 'Vikrum Shah', 'Sofia Lebedeva', 'Adam Barnett', 'Gardo Versoza', 'Maria Bello', 'Derek Luke', 'Gregory Shelby', 'Rick Hurst', 'Simon Abkarian', 'Phil Redrow', 'Bruce Holman', 'Jim Belushi', 'Josh Lawson', 'Abigail Cruttenden', 'Zinedine Soualem', 'Philip Bruns', 'Nancy Baldwin', 'Debra Christofferson', 'Arielle Kebbel', 'Elliott Spiers', 'Wes Studi', 'Albert Salmi', 'James Brown', 'Salli Richardson-Whitfield', 'Elisabeth Margoni', 'Imogen Toner', 'Ralf Moeller', 'Bridgette Wilson', 'Louise Lombard', 'Antony Coleman', 'Percy Matsemela', 'Frank Medrano', 'Charles Robinson', 'Orla Brady', 'Ian Roberts', 'Jean-Claude Dreyfus', 'Miguel √Ångel Mu√±oz', 'Larry Neumann Jr.', 'Shawn Rougeron', 'Ben Schnetzer', 'Jason Butler Harner', 'Valarie Trapp', 'John Candy', 'Cristiana Capotondi', 'William Hope', 'Josh Pais', 'Buddy Ebsen', 'Ray Wise', 'Jeremy Sisto', 'Jeffrey Scott Jensen', 'Margarita Calahorra', 'Robert Beltran', 'Nicole Mu√±oz', 'Stephen Graham', 'Odile Corso', 'Byron Minns', 'Jared Harris', 'Brittany Byrnes', 'Jonathan Taylor Thomas', 'Omar Sy', 'Jonathan Cherry', 'Arthur Burghardt', 'Christopher Klucsarits', 'Jenny Marie Mitchell', 'Ukee Washington', 'Bruce Cohen', 'Vivien Li Meng', 'Frances Foster', 'Keiichi Enomoto', 'Peter Riegert', 'Anthony LaPaglia', 'Andy Garc√≠a', 'Marciee Drake', 'William Calvert', 'Lorraine Nicholson', 'Zoe Kazan', 'Ted Grossman', 'Tilda Swinton', 'Jocelyn Ayanna', 'Deborah Alcorn', 'Vincent Gardenia', 'Matt Bennett', 'Zhao Tao', 'Joan Camden', 'Wang Baoqiang', 'Fernando Wagner', 'Fatima El Bahraquy', 'Tim Russ', 'Evan Jones', 'Kazuki Namioka', 'Daniel Greene', 'Rose Leslie', 'Tony Morelli', 'Calvin C. Winbush', 'Viktor Shamirov', 'Gloria Hylton', 'Mitsuru Miyamoto', 'Emma Bell', 'Alden Ray', 'Rob Morrow', 'Damian Jewan Lee', 'Derrick Lassic', 'Ali Tataryn', 'Eric Roberts', 'Michael Monks', 'David Klein', 'Ed Harris', 'Larry Reynolds', 'Judy Greer', 'Andreas Katsulas', 'Hannah Fierman', 'Jennessa Rose', 'Maurice B√©nichou', 'Jeff Bridges', 'Rick Prieto', 'Gary Hetherington', 'Max Pfeifer', 'Jeffrey J. Dashnaw', 'Jacques Sereys', 'Mitch Holleman', 'Kieran Culkin', 'Mark Chiriboga', 'Ernie Reyes, Jr.', 'Will Brittain', 'Danny Hoch', 'Ethan Laidlaw', 'Jane Fergus', 'Eric Pohlmann', 'Lieux Dressler', 'Mushtaq Khan', 'Alun Armstrong', 'Emma James', 'Kika Markham', 'Brian Cox', 'Ram√≥n Rodr√≠guez', 'Katsu Nojiri', 'Beppe Abela', 'Karl Wiedergott', 'Marc Akerstream', 'Jeremy Northam', 'J.E. Freeman', 'Kate Mara', 'Trey Wilson', 'Philippa Fordham', 'Sara Ramirez', 'Missi Pyle', 'Dan Fitzgerald', 'Emily Zachary', 'McKaley Miller', 'Maggie Elizabeth Jones', 'Masato Yamanouchi', 'Raugi Yu', 'Brin Berliner', 'Ad van Kempen', 'Brad Loree', 'Pat Skipper', 'Judith El Zein', 'Christopher Lloyd', 'Shane Rimmer', 'Josh Gad', 'Donald Gantry', 'Gloria Lynne Henry', 'Donald Adams', 'Cuba Gooding Jr.', 'Rena Owen', 'Thelma Louise Carter', 'Meredith Baxter', 'Katie Keating', 'George Fernandez', 'Jimmy Bennett', 'Art Garfunkel', "Carroll O'Connor", 'No√©mie Lenoir', 'David Landsberg', 'Amaurys Rodriguez', 'Ricky Schroder', 'Tyler Cravens', 'Bryan Massey', 'Rubens Santos', 'Simon Pegg', 'Matt Blackwell', 'Raymond Forchion', 'Nancy Anderson', 'Steve J. Spears', 'Skye McCole Bartusiak', 'Dominique Moceanu', 'Bill Clinton', 'Albert Dupontel', 'Claire van der Boom', 'Helmert Woudenberg', 'Jacqueline Gadsden', 'Nanako Matsushima', 'Michael Clay', 'Sam Robards', 'Matthew Fenton', 'Sinbad', 'Jimmy Bridges', 'R. Keith Harris', 'Leonardo DiCaprio', 'Neil Vipond', 'Sherilyn Fenn', 'Treat Williams', 'Pat Henning', 'Alejandro Estornel', 'Lorna Scott', 'Natalia Sokolova', 'Garrett Hedlund', 'Missy Crider', 'Tim Mirkovich', 'Daniil Spivakovskiy', 'Thomas Lennon', 'Wendy Watanabe', 'Stephen Pearlman', 'Peter Bryant', 'Toni Reimer', 'Rebecca Pidgeon', 'P.H. Moriarty', 'Elizabeth Gracen', 'Ernest James', 'Bruno Solo', 'Susan Sarandon', 'Mark DeLisle', 'Sushant Singh', 'Andrew Tiernan', 'Ian Fried', 'Mim√≠ Mu√±oz', 'Mammootty', 'Juan Socorra Vega', 'Nicholas Braun', 'Matthias Habich', 'Emma Levie', 'Fernando Teixeira', 'Winona Ryder', 'Jon Gries', 'Adrian Lamo', 'Philip Seymour Hoffman', 'Paul Calderon', 'Richard Liberty', 'Mae Busch', 'Andy Taylor', 'Elizabeth Berkley', 'Dan Gilvezan', 'Laura Hart', 'Jordan Butterill', 'Roy Engel', 'Steve Frye', 'Sandrine Bonnaire', 'June Diane Raphael', 'Jason Bateman', 'Michole Briana White', 'Robert Ellenstein', 'Matthew Corbett Davis', 'Michael J. Pagan', 'Ian Harcourt', 'Herb Tanney', 'Wayne Knight', 'Trevor Howard', 'Eddy Rice Jr.', 'Ted Knight', 'Charlotte Rampling', 'Evan Saucedo', 'Iemasa Kayumi', 'Monty Montgomery', 'Steve Zahn', 'Danny McBride', 'Georg Nikoloff', 'Kwame Kwei-Armah', 'Tanya Clarke', 'Kiko Mizuhara', 'Nina Arianda', 'Yutaka Izumihara', 'Max Thieriot', 'Glen Powell', 'Conrad Dunn', 'Hayden Tank', 'Anthony Skrimshire', 'Michael Chernus', 'Laura Marano', 'Charlie Sheen', 'Stephen Lang', 'Stuart Greer', 'Ir√°n Castillo', 'Jeremy Piven', 'Dennis McCormack', 'Perrette Souplex', 'Wanda De Jesus', 'Jason David Frank', 'Yelena Solovey', 'Jean-Pierre Cassel', 'Hera Hilmar', 'Victor Talmadge', 'Jacob Latimore', 'Leonard Carey', 'David Alvarado', 'Arthur Hill', 'Lu Zhong', 'Nehemiah Persoff', 'Pilar Gil', 'Steven Berkoff', 'Gilles Lellouche', 'Victoria Jackson', 'Treyton Augustus Walcot', 'Marcia DeBonis', 'Michel Vuillermoz', 'Emma Bunton', 'Eva Williams', 'Katie Boland', 'Danny Trejo', 'Gary Gulman', 'Anand Upadhyaya', 'Mark Benninghoffen', 'Suzanne Ford', 'Frank McRae', 'Libby Taylor', 'Pedro Cardoso', 'Lee Burns', 'Chelcie Ross', 'Denise Dal Vera', 'Emile Hirsch', 'Jim Cantafio', 'John Randolph', 'Mike Hagerty', 'Lindsay Crouse', 'Adam Bocknek', 'John B. Lowe', 'Laura Linney', 'Kerry Kletter', 'Tzi Ma', 'Joe Chrest', 'Cate Blanchett', 'Sadik Eksi', 'Ronnie Schell', 'Melinda Fleming', 'Zhang Jin Zhan', 'Benoit Priest', 'Trula M. Marcus', 'Dennis Garber', 'Mourad Frarema', "Ivan 'Flipz' Velez", 'Monique van de Ven', 'Paul Adelstein', 'Ahmet Zappa', 'Megan Fox', 'Ingvar Eggert Sigur√∞sson', 'Ray Romano', 'Sy Richardson', 'Mark Killeen', 'Beau Paley', 'Dennis Lafond', 'Carey Lowell', 'Camilla Belle', 'Ashlynn Ross', 'Juston Street', 'Robert Russell', 'Geena Davis', 'Patina Miller', 'Beno√Æt Magimel', 'George Clinton', 'Andrew S. Gilbert', 'Matthew Gray Gubler', 'Mel Hampton', 'Bobby Smalldridge', 'Ponnambalam', 'Gamil Ratib', 'Christopher Lee Philips', 'Anson Mount', 'Glenis Levestam', 'Chris Evans', 'Myles Cleveland', 'Brian Caspe', 'Dean Monroe McKenzie', 'JR Bourne', 'Takayuki Yamada', 'Jansen Panettiere', 'Brandon Rush', 'Anointing Lukola', 'Reginald Owen', 'Florence Hartigan', 'Lauren Saarimaki', 'C.J. Byrnes', 'Peter Houghton', 'Tammy Monica Gegamian', 'Megan Albertus', 'Gerry Mendicino', 'James Robert Miller', 'Oscar Rowland', 'Iggy Pop', 'Clayton Hill', 'Vise Vitale', 'Demi√°n Bichir', 'Lawrence Gilliard Jr.', 'Randy Savage', 'Nestor Serrano', 'Graham Norton', 'Monique Ganderton', 'Haruna Honcoopova', 'Henrietta Clemett', 'Nick Barbaro', 'Mary Lou Simo', 'Ralph Fiennes', 'Tom Arnold', 'Bethel Leslie', 'Paul Guilfoyle', 'Duncan Fraser', 'Robert Manne', 'Robert Donner', 'Shane Johnson', 'Kalla Pasha', 'Brian Keith', 'Dorothy Malone', 'Kamran Dehghan', 'Janet Jones', 'Bethan Coomber', 'Sava Lolov', 'Joey Kramer', 'Ellie Kendrick', 'Brian L. Keaulana', 'Ray McKinnon', 'Efrem Zimbalist, Jr.', 'Joseph Fiennes', 'Curt Hennig', 'MIchael P. Cahill', 'Jeff Buckner', 'Sharon J. Robinson', 'Dabney Coleman', '√âlisabeth Vitali', 'Yoko Maki', 'Ulrike Krumbiegel', 'Paul Rae', 'DeForest Kelley', 'Molly Picon', 'Wayne Newton', 'M.J. Kang', 'Emma Elle Roberts', 'Joe Schmidt', 'Cecilia L. Salinas', 'Roman Radov', 'Jonathan Adler', 'David Downer', 'Nicholas Guest', 'Harry Dean Stanton', 'Donnie Yen', 'Robert Cavanah', 'Vivian Bonnell', 'Paul Newman', 'Britt Barrett', 'Brad Beyer', 'Tim Kelleher', 'Ruben Rabasa', 'Cory Wojcik', "Dick O'Neill", 'Emily Browning', 'Vince Vaughn', 'Eduardo An√≠bal Gonz√°lez Hern√°ndez', 'Michael Ienna', 'Richard Wells', 'Eric Sheffer Stevens', 'Chris Pine', 'Bobby Joe McFadden', 'M√≠a Maestro', 'Scott Powell', 'Erin Simms', 'Julie Austin', 'David Frutos', 'Holmes Osborne', 'Jos√© Carlos Rodr√≠guez', 'Donita Sparks', 'Zachary Gordon', 'Pooch Hall', 'Agust√≠n Gonz√°lez', 'Shinji Ikefuji', 'Rita Davies', 'Ralph Waite', 'Anthony G. Schmidt', 'Geeta Masi', 'Ralph Redpath', 'Eileen Davies', 'Borja Echevarr√≠a', 'Christian Clavier', 'Andrei Panin', 'Igor Jijikine', 'Garry Cooper', 'Katie Sagona', 'Simon Chandler', 'Michael Edward-Stevens', 'David Warshofsky', 'Fran Kranz', 'Elly Jackson', 'Nicole Hansen', 'Lori Richardson', 'Denise Kirby', 'Silas Carson', 'Ron Barker', 'Frankie Van', 'Philip Bourneuf', 'Theo Morrissey', 'Franco Solazzi', 'Roy Thinnes', 'Viktoria Zakharyanova', 'Maximiliano Hern√°ndez', 'Kayla Blake', 'Russ Conway', 'Kristopher Bos', 'David Duchovny', 'Brenda Wehle', 'Claire Davenport', 'Robert Shaw', 'Jasper Cole', 'Audrey Marnay', 'Nate Lang', 'David Terrell', 'Dan Harris', 'Masachika Ichimura', 'Tjitske Reidinga', 'Arthur Keegan', 'Mary Elizabeth Pohl', 'Bruce A. Young', 'Raj Babbar', 'Javan Kaiama', 'Olutunji Ebun-Cole', 'Jeanne Tripplehorn', 'Jourdan Dunn', 'Inmo Yuon', 'Ken Drury', 'Joe Don Baker', 'Sherry Lynn', 'Kevin Dunn', 'Maggie Daniels', 'Thomas Middleditch', 'Chae An', 'Ashley Taylor-Rhys', 'Tamsen McDonough', 'Clark Middleton', 'Tokio Emoto ', 'Supreet', 'Leonard Roberts', 'Eric Curtis', 'Minka Kelly', 'Louis McIntosh', 'Stanley B. Herman', 'Wes Bentley', 'Tony Devon', 'M.C. Gainey', 'Adam Curry', 'Susan Peretz', 'Richard Jeni', 'Lawrence Dobkin', 'Russell Means', 'Kristen Rakes', 'Janet Hoskins', 'Shruti Bapna', 'John Cullum', 'Sharon Stone', 'Jerry Inzerillo', 'Julie Kavner', 'Josie Maran', 'Robert Drivas', 'P.C. Frieberg', 'Thomas Kopache', 'Rickie Lee Jones', 'Jill St. John', 'John Heard', 'Peter Arne', 'Jessica Stroup', 'Paul Cram', 'Geraldine McEwan', 'Nat Benchley', 'Arsenio Hall', 'Diana Lewis', 'Fred Durst', 'Carsten Norgaard', 'John Michael Higgins', 'Angela Goethals', 'Andrew Weir', '–≠—Ä–∏–∫–∞ –≠–ª–µ–Ω–∏–∞–∫', 'Jack Harris', 'Debra Monk', 'Dave Goelz', 'Sergei Bezrukov', 'Chris Rebello', 'Cung Le', 'John Hyams', 'Anthony Nocerino', 'Cillian Murphy', 'Salvatore H. Tornabene', 'Kevin Glikmann', 'Robert Swenson', 'Monica McSwain', 'Robert Bailey Jr.', 'Debbie Entin', 'Srividhya', 'Jon Voight', 'Tetsuo Mizutori', 'Pierre-Fran√ßois Martin-Laval', 'Jimmie F. Skaggs', 'Sterling Jerins', 'Jihwan Kim', 'Jake Feagai', 'Jack Thibeau', 'Desmond Harrington', 'Birgit Minichmayr', 'Jody Kono', 'Clu Gulager', 'Lidia Vitale', 'Ranvir Shorey', 'Pancho Graham', 'Carl Toop', 'Kenichi Matsuyama', 'Tom Bosley', 'Emma Stone', 'Timothy Lyle', 'Masataka Kubota', 'Sean Carrigan', 'Jean-Fran√ßois Cayrey', 'Crusoe Kurddal', 'Pedro Lovell', 'Yeardley Smith', 'Morris Zuckerman', 'Jane Horrocks', 'Leo Rogstad', 'Andrew McNee', 'Olesya Zheleznyak', 'Joel Bissonnette', 'Mauricio Gon√ßalves', 'Mahito Tsujimura', 'Michael Pe√±a', 'Mary Gross', 'Kate Winslet', 'Rita Taggart', 'Marty Wright', 'Sandi Shackelford', 'Garvin Cross', 'Jean Del Val', 'Dan Gifford', 'Caroline Sunshine', 'Richard Lexsee', 'John Dennis Johnston', 'Arata Furuta', 'James Badge Dale', 'Diane Nelson', 'Cullen Moss', 'Rusty McClennon', 'Anie Pascale', 'Job Daniel', 'Jay Thomas', 'Cheech Marin', 'Gretchen Mol', 'Sven Melander', 'Angela Bishop', 'Tiny Ward', 'Marshall Bell', 'Jean-Michel Correia', "Charles 'Jester' Poston", 'Cary Elwes', 'John P. Fertitta', 'Wren T. Brown', 'Ricky Gervais', 'Walid Afkir', 'Larry King', 'Darcy DeMoss', 'David House', 'Emilio Estevez', 'Cynthia Nixon', 'Beau James', 'Grace Dove', 'Nicole Boccumini', 'Mel Raido', 'Stephen Dimopoulos', 'Â∫∑ÊÆøÂÆè', 'Wings Hauser', 'Dave Hoover', 'Terry Kinney', 'Jason Isaacs', 'Mary Ann Rodgers', 'Castulo Guerra', 'Thomas Thieme', 'Zane Lamprey', 'Joseph Mawle', 'Clark Duke', 'Matthias Schoenaerts', 'Catherine McCormack', 'Marybeth Fisher', 'Margaret Klenck', 'C.J. Vana', 'Daniel Radcliffe', 'Richard Petty', 'Aleksey Dmitriev', 'Lana Wood', 'Bernard Padden', 'Kim Kondrashoff', 'Claudia Newman', 'Kelly Lind', 'Dakota Lupo', 'Spencer Garrett', 'Faleolo Alailima', 'Al Silvani', 'Romano Orzari', 'Brendan Titley', 'John Amos', 'Amanda Fairbank-Hynes', 'Paul Dooley', 'Scott Jackson', 'Charles Malik Whitfield', 'Buffy Davis', 'David Joseph Martinez', 'Joel McCrary', 'Philip Shelley', 'Isaac Sharry', 'Ariel Winter', 'Yvonne Thomas', 'Charlotte Bradley', 'Angelina Estrada', 'Mary Jo Catlett', 'Robert A. Ringler', 'Alisa Allapach', 'Richard Chamberlain', 'Luke Roberts', 'Liza Minnelli', 'Jacques Boko', 'Jean Paul Gaultier', 'Orestes Matacena', 'Jan Cornet', 'William Hurt', 'Yuriy Kutsenko', 'Dan Albright', 'Marton Csokas', 'Malcolm Scott', 'Taylor Ashley Murphy', 'Bobby Cannavale', 'Izzie Coffey', 'Lochlyn Munro', 'Benny Ciaramello', 'L.B. Williams', 'Mark Thomason', 'Omid Abtahi', 'Christian Barbier', 'Robert Jayne', 'Mervyn Lilo', 'Cl√°udia Abreu', 'Doug E. Doug', 'Lara Stone', 'È´òÊ°•‰∏ÄÁîü', 'Lowell Ganz', 'Mina Sundwall', 'Teresa Hurtado de Ory', 'Jennifer Jason Leigh', 'Tim Key', 'Ehud Bleiberg', 'Kaitlyn Maher', 'Robert Irvin Elliott', 'Donal Beecher', 'Mary-Charles Jones', 'Marshall B. Gage', 'Courtney B. Vance', 'Audrey Lamy', 'Andrew Bridgmont', 'Diane Lane', 'Todd Phillips', 'Jack Pyland', 'Neville Brand', 'Chris Heuisler', 'Thomas Con

In [36]:
actor_df=pd.DataFrame(movie_actor,columns=['cast'])

In [39]:
# Actor with the Most number of the film
actor_df.value_counts().sort_values(ascending=False)

cast
Keith David        8
Kathy Bates        7
J.K. Simmons       7
Chris Cooper       7
Brendan Gleeson    7
                  ..
Val Maloku         1
Val McDow          1
Valarie Trapp      1
Valdeci Junior     1
Victor Ha√Øm       1
Name: count, Length: 8701, dtype: int64