In [ ]:
import numpy as np
import pandas as pd

In [ ]:
pd.__version__

'2.2.2'

In [ ]:
a = pd.Series([1,2,3,4,5])
type(a)

pandas.core.series.Series

In [ ]:
print(a)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
a = pd.Series([1,2,3,4,5], index =['a','b','c','d','e'])
print(a)

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
print(a['a'])

1

In [ ]:
print(a['c'])

3

In [ ]:
print(a['e'])

5

In [ ]:
a = np.random.randint(10,20,(2,2))

In [ ]:
df=pd.DataFrame(a)

In [ ]:
print(df)

    0   1
0  19  11
1  19  13

In [ ]:
df=pd.DataFrame(a,columns=['apple','Oranges'],index=['1','2'])
print(df)

   apple  Oranges
1     19       11
2     19       13

In [ ]:
a=[['Rohan',20],['Mohan',21],['Sohan',22]]
df = pd.DataFrame(a)
df

       0   1
0  Rohan  20
1  Mohan  21
2  Sohan  22

In [ ]:
df= pd.DataFrame(a,columns=['Name','Age'],index=['1','2','3'])
print(df)
df

    Name  Age
1  Rohan   20
2  Mohan   21
3  Sohan   22

    Name  Age
1  Rohan   20
2  Mohan   21
3  Sohan   22

Creating dataframe with the help of the array of 51 rows and 5 columns

In [ ]:
a = np.random.randint(11,21,(51,5))
df = pd.DataFrame(a,columns=['a','b','c','d','e'])
df

     a   b   c   d   e
0   13  18  15  11  17
1   12  17  20  15  18
2   19  12  12  12  14
3   16  11  17  17  18
4   13  15  11  16  15
5   15  12  11  11  19
6   17  19  11  15  18
7   14  18  11  19  11
8   20  15  15  17  15
9   12  11  16  16  15
10  20  14  17  12  19
11  20  18  16  18  18
12  14  20  17  11  20
13  12  16  12  16  13
14  11  14  20  13  12
15  15  20  13  13  12
16  19  20  12  15  16
17  13  15  12  18  11
18  12  20  11  18  19
19  12  12  14  15  18
20  14  17  19  11  19
21  11  20  18  13  12
22  12  17  18  12  13
23  17  16  14  11  11
24  15  14  18  17  20
25  18  12  13  16  20
26  14  17  16  14  19
27  13  20  15  13  13
28  13  14  15  20  15
29  18  13  11  14  14
30  12  17  11  17  12
31  14  13  12  12  14
32  13  19  14  16  19
33  19  20  18  18  11
34  14  11  16  16  17
35  12  16  18  11  15
36  19  13  20  14  13
37  20  15  20  11  17
38  12  19  18  13  20
39  20  15  11  18  20
40  15  15  17  17  16
41  14  15  18  19  16
42  17  14  16  19  11
43  15  15  20  18  12
44  15  19  20  19  19
45  18  16  18  14  14
46  12  12  11  16  18
47  13  18  11  11  18
48  12  17  15  13  14
49  17  14  16  19  19
50  16  11  11  18  15

In [ ]:
a = {'name':['Virat','Visheshata','Kunj'],'age':['21','21','22']}
df=pd.DataFrame(a)
df

         name age
0       Virat  21
1  Visheshata  21
2        Kunj  22

In [ ]:
df.tail

<bound method NDFrame.tail of          name age
0       Virat  21
1  Visheshata  21
2        Kunj  22>

In [ ]:
df.tail(7)

     a   b   c   d   e
44  15  19  20  19  19
45  18  16  18  14  14
46  12  12  11  16  18
47  13  18  11  11  18
48  12  17  15  13  14
49  17  14  16  19  19
50  16  11  11  18  15

In [ ]:
df.columns

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 5 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   a       51 non-null     int64
 1   b       51 non-null     int64
 2   c       51 non-null     int64
 3   d       51 non-null     int64
 4   e       51 non-null     int64
dtypes: int64(5)
memory usage: 2.1 KB

Original DataFrame connection and other Functionalities

In [ ]:
path = '/content/drive/MyDrive/Colab Notebooks/imdb_data.csv'

In [ ]:
df = pd.read_csv(path)
df.head(7)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,2/20/15,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,8/6/04,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,10/10/14,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,2/5/09,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,8/6/87,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,8/30/12,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  runtime                2998 non-null   float64
 15  spoken_languages       2980 non-null   object
 16  status                 3000 non-null   object
 17  tagline                2403 non-null   object
 18  title                  3000 non-null   object
 19  Keywords               2724 non-null   object
 20  cast                   2987 non-null   object
 21  crew                   2984 non-null   object
 22  revenue                3000 non-null   int64
dtypes: float64(2), int64(3), object(18)
memory usage: 539.2+ KB

In [ ]:
df.shape

(3000, 23)

In [ ]:
df.describe()

                id        budget   popularity      runtime       revenue
count  3000.000000  3.000000e+03  3000.000000  2998.000000  3.000000e+03
mean   1500.500000  2.253133e+07     8.463274   107.856571  6.672585e+07
std     866.169729  3.702609e+07    12.104000    22.086434  1.375323e+08
min       1.000000  0.000000e+00     0.000001     0.000000  1.000000e+00
25%     750.750000  0.000000e+00     4.018053    94.000000  2.379808e+06
50%    1500.500000  8.000000e+06     7.374861   104.000000  1.680707e+07
75%    2250.250000  2.900000e+07    10.890983   118.000000  6.891920e+07
max    3000.000000  3.800000e+08   294.337037   338.000000  1.519558e+09

In [ ]:
df.iloc[0:6,0:7]

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en

In [ ]:
df['title']

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
df[['title','genres','original_language']]

,title,genres,original_language
0,Hot Tub Time Machine 2,"[{'id': 35, 'name': 'Comedy'}]",en
1,The Princess Diaries 2: Royal Engagement,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en
2,Whiplash,"[{'id': 18, 'name': 'Drama'}]",en
3,Kahaani,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",hi
4,Marine Boy,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",ko
...,...,...,...
2995,Chasers,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en
2996,We Are the Best!,"[{'id': 18, 'name': 'Drama'}, {'id': 10402, 'n...",sv
2997,The Long Kiss Goodnight,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",en
2998,Along Came Polly,"[{'id': 35, 'name': 'Comedy'}, {'id': 10749, '...",en
2999,Abduction,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",en

In [ ]:
df.loc[ :7,['title','genres','original_language']]

,title,genres,original_language
0,Hot Tub Time Machine 2,"[{'id': 35, 'name': 'Comedy'}]",en
1,The Princess Diaries 2: Royal Engagement,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",en
2,Whiplash,"[{'id': 18, 'name': 'Drama'}]",en
3,Kahaani,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",hi
4,Marine Boy,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",ko
5,Pinocchio and the Emperor of the Night,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",en
6,The Possession,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",en
7,Control Room,"[{'id': 99, 'name': 'Documentary'}]",en

In [ ]:
df['popularity']

0        6.575393
1        8.248895
2       64.299990
3        3.174936
4        1.148070
          ...
2995     9.853270
2996     3.727996
2997    14.482345
2998    15.725542
2999    10.512109
Name: popularity, Length: 3000, dtype: float64

In [ ]:
df[df['popularity']==df['popularity'].max()][['title','popularity']]

            title  popularity
518  Wonder Woman  294.337037

In [ ]:
df[df['original_language']=='hi']

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,release_date,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,3/9/12,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000
213,214,NaN,6700000,"[{'id': 28, 'name': 'Action'}]",NaN,tt2077833,hi,राउडी राठौर,Low-life thief Shiva and top-cop Vikram Rathor...,1.312833,...,6/1/12,143.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Rowdy Rathore,"[{'id': 1721, 'name': 'fight'}, {'id': 8015, '...","[{'cast_id': 11, 'character': 'Shiva / Vikram ...","[{'credit_id': '52fe4a0bc3a36847f81b58a9', 'de...",31000000
371,372,NaN,13100000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",http://www.thankyouthefilm.com/,tt1720254,hi,Thank You,The film is about three husbands having affair...,1.417392,...,4/8/11,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Husbands will say sorry ... Wives will say tha...,Thank You,NaN,"[{'cast_id': 1, 'character': 'Kishen', 'credit...","[{'credit_id': '52fe4651c3a368484e08a13f', 'de...",4100000
401,402,NaN,3000000,"[{'id': 18, 'name': 'Drama'}, {'id': 36, 'name...",NaN,tt0319736,hi,The Legend of Bhagat Singh,The Legend of Bhagat Singh is a 2002 Indian hi...,0.904409,...,6/7/02,155.0,"[{'iso_639_1': 'pa', 'name': 'ਪੰਜਾਬੀ'}, {'iso_...",Released,NaN,The Legend of Bhagat Singh,NaN,"[{'cast_id': 12, 'character': 'Bhagat K. Singh...","[{'credit_id': '52fe44849251416c9101372f', 'de...",6000000
419,420,NaN,3750000,"[{'id': 35, 'name': 'Comedy'}, {'id': 10769, '...",http://www.atithithefilm.com/,tt1578116,hi,Atithi Tum Kab Jaoge,Atithi Tum Kab Jaoge? is the story of Puneet a...,0.597058,...,2/26/10,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,"Dear Guest, When Will You Leave?",NaN,"[{'cast_id': 1, 'character': 'Puneet, Pappu', ...","[{'credit_id': '5647c0359251413ade004b4d', 'de...",5000000
481,482,NaN,10500000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.cc2c-thefilm.com/,tt1091229,hi,Chandni Chowk To China,"Based in Delhi's Chandni Chowk, orphaned Sidhu...",1.970481,...,1/16/09,149.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Chandni Chowk To China,"[{'id': 4344, 'name': 'musical'}, {'id': 10540...","[{'cast_id': 10, 'character': 'Sidhu', 'credit...","[{'credit_id': '52fe43d2c3a368484e00004d', 'de...",9400000
585,586,NaN,10400000,"[{'id': 18, 'name': 'Drama'}]",NaN,tt5074352,hi,दंगल,Dangal is an extraordinary true story based on...,8.792104,...,12/23/16,161.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dangal,"[{'id': 5565, 'name': 'biography'}, {'id': 597...","[{'cast_id': 0, 'character': 'Mahavir Singh Ph...","[{'credit_id': '5714ef3f92514146c80003ea', 'de...",310000000
627,628,NaN,16000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",http://www.yashrajfilms.com/Movies/MovieIndivi...,tt3495026,hi,Fan,The story of a fan whose world completely revo...,5.127876,...,4/15/16,142.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,World's biggest superstar got the universe's b...,Fan,"[{'id': 1523, 'name': 'obsession'}, {'id': 981...","[{'cast_id': 1, 'character': 'Gaurav Chandna /...","[{'credit_id': '569bc0de9251415e7000003c', 'de...",29251596
671,672,NaN,6400000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.anjaanaanjaani.erosentertainment.com,tt1499201,hi,Anjaana Anjaani,Akash (Ranbir Kapoor) and Kiara (Priyanka Chop...,1.822940,...,9/24/10,151.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,All the greatest love stories...are between st...,Anjaana Anjaani,"[{'id': 1252, 'name': 'suicide attempt'}, {'id...","[{'cast_id': 2, 'character': 'Kiara', 'credit_...","[{'credit_id': '58a2fb2cc3a3682902007108', 'de...",5900000
695,696,NaN,1,"[{'id': 10749, 'name': 'Romance'}, {'id': 53, ...",NaN,tt0374271,hi,Tere Naam,"Lower Caste Radhey Mohan is a no good slacker,...",1.280455,...,8/15/03,132.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Unfortunately a true love story,Tere Naam,NaN,"[{'cast_id': 3, 'character': 'Radhe Mohan', 'c...","[{'credit_id': '52fe491ec3a36847f8189cfb', 'de...",2
771,772,NaN,9000000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",http://kaminey.utvnet.com/,tt1274295,hi,Kaminey,Guddu and Charlie are identical twins born and...,2.089842,...,8/14/09,135.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}]",Released,Thif monfoon. Difcover your mean fide.,Kaminey,"[{'id': 14636, 'name': 'india'}]","[{'cast_id': 1, 'character': 'Charlie / Guddu'...","[{'credit_id': '52fe43f4c3a368484e007b65', 'de...",18130000
840,841,NaN,10721568,"[{'id': 18, 'name': 'Drama'}]",https://www.facebook.com/foxstarhindi/,tt5286444,hi,नीरजा,Neerja is a portrayal on the life of the coura...,1.686250,...,2/19/16,122.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Fear Gave Her Courage,Neerja,"[{'id': 4245, 'name': 'hijacking'}, {'id': 967...","[{'cast_id': 0, 'character': 'Neerja Bhanot', ...","[{'credit_id': '5692588192514115bf001d11', 'de...",2978994
848,849,NaN,6400000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt2359810,hi,रान्झाना,A small-town boy needs to break through the cl...,1.856101,...,6/21/13,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Raanjhanaa,"[{'id': 10048, 'name': 'unrequited love'}, {'i...","[{'cast_id': 1, 'character': 'Kundan', 'credit...","[{'credit_id': '52fe4c799251416c910f611d', 'de...",18000000
970,971,NaN,4200000,"[{'id': 10749, 'name': 'Romance'}, {'id': 28, ...",NaN,tt3142232,hi,Heropanti,Rising from present India in the conflicting e...,2.031919,...,5/23/14,146.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Heropanti,NaN,"[{'cast_id': 1, 'character': 'Bablu', 'credit_...","[{'credit_id': '53baa148c3a3685eb4006e29', 'de...",10000000
1004,1005,NaN,1000000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt2350496,hi,Dabba,A mistaken delivery in Mumbai's famously effic...,10.766409,...,9/19/13,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,The Lunchbox,NaN,"[{'cast_id': 2, 'character': 'Saajan Fernandes...","[{'credit_id': '5476f65b9251415d7a0016eb', 'de...",4235151
1491,1492,NaN,5500000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt3767372,hi,Piku,"A road trip to Kolkata brings Piku, an archite...",2.942711,...,5/8/15,123.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Motion Se Hi Emotion,Piku,NaN,"[{'cast_id': 0, 'character': 'Bashkor Banerjee...","[{'credit_id': '5551de509251416a93005e01', 'de...",22159216
1572,1573,NaN,9100000,"[{'id': 53, 'name': 'Thriller'}, {'id': 28, 'n...",http://www.rememberghajini.com/,tt1166100,hi,Ghajini,Sanjay a rich tycoon suffering from short term...,4.239080,...,12/25/08,183.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Ghajini,"[{'id': 331, 'name': 'tattoo'}, {'id': 154785,...","[{'cast_id': 12, 'character': 'Sanjay Singhani...","[{'credit_id': '52fe45c99251416c75062659', 'de...",76000000
1640,1641,NaN,4600000,"[{'id': 36, 'name': 'History'}, {'id': 28, 'na...",NaN,tt2356180,hi,Bhaag Milkha Bhaag,"The true story of the ""Flying Sikh"" world cham...",4.342418,...,7/12/13,186.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Now you will see his Real Story.,Bhaag Milkha Bhaag,"[{'id': 795, 'name': 'running'}, {'id': 1721, ...","[{'cast_id': 1, 'character': 'Milkha Singh', '...","[{'credit_id': '52fe4d1ac3a368484e1d74af', 'de...",25000000
1656,1657,NaN,18000000,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",http://www.chennaiexp2013.com/chennaiexpress.aspx,tt2112124,hi,Chennai Express,Rahul embarks on a journey to a small town in ...,4.193560,...,8/9/13,141.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,Ready... Steady... Po!,Chennai Express,"[{'id': 4412, 'name': 'grandfather'}, {'id': 4...","[{'cast_id': 2, 'character': 'Rahul Mithaiwala...","[{'credit_id': '581e56659251410f4f00f125', 'de...",62000000
1694,1695,NaN,521873,"[{'id': 53, 'name': 'Thriller'}, {'id': 80, 'n...",NaN,tt5662932,hi,रमन राघव २.०,Set in present day Mumbai the story follows th...,1.668794,...,6/24/16,127.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Raman Raghav 2.0,"[{'id': 10024, 'name': 'psychopathic killer'},...","[{'cast_id': 6, 'character': 'Ramanna (Raman)'...","[{'credit_id': '57160f17c3a3682f450033eb', 'de...",1013926
1719,1720,NaN,4437508,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",http://www.utvgroup.com/motion-pictures/coming...,tt2082197,hi,Barfi!,He is cute. He's shrewd. The girls love him. T...,3.779077,...,9/14/12,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Barfi,"[{'id': 1646, 'name': 'autism'}]","[{'cast_id': 5, 'character': 'Jhilmil Singh', ...","[{'credit_id': '5926294cc3a36877fd014ce9', 'de...",2804874
1729,1730,NaN,5200000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0164538,hi,दिल से,The clash between love and ideology is portray...,1.891138,...,8/22/98,163.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Dil Se..,"[{'id': 258, 'name': 'bomb'}, {'id': 321, 'nam...","[{'cast_id': 2, 'character': 'Amarkanth Varma'...","[{'credit_id': '57b53e789251410918000155', 'de...",13000000
1732,1733,"[{'id': 419784, 'name': 'Masti Collection', 'p...",5500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt2476154,hi,Grand Masti,"Amar, Prem and Meet are longtime friends who h...",1.250293,...,9/13/13,140.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,The Masti Boys are Back,Grand Masti,NaN,"[{'cast_id': 2, 'character': 'Amar', 'credit_i...","[{'credit_id': '52fe4db49251416c7513dd27', 'de...",47000000
1766,1767,NaN,0,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt0290326,hi,Tum Bin,"Shekhar, a businessman, accidentally kills his...",0.371679,...,7/13/01,158.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Love Will Find the Way,Tum Bin,"[{'id': 128, 'name': 'love triangle'}, {'id': ...","[{'cast_id': 1, 'character': 'Shekhar Malhotra...","[{'credit_id': '52fe46efc3a368484e0abfaf', 'de...",1486992
1948,1949,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 80, 'nam...",NaN,tt0476805,hi,मालामाल वीकली,Lilaram sells lottery tickets and one customer...,1.479018,...,3/10/06,138.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Malamaal Weekly,NaN,"[{'cast_id': 1, 'character': 'Kanhaiya', 'cred...","[{'credit_id': '592dd1fbc3a36808c3000dd9', 'de...",204
1987,1988,NaN,0,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0347304,hi,कल हो ना हो,Naina is a very serious girl with a very serio...,5.584308,...,11/27/03,186.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Kal Ho Naa Ho,"[{'id': 242, 'name': 'new york'}, {'id': 958, ...","[{'cast_id': 8, 'character': 'Aman Mathur', 'c...","[{'credit_id': '52fe43b6c3a36847f8069c57', 'de...",13200241
1989,1990,"[{'id': 20970, 'name': 'Sarkar Collection', 'p...",1900000,"[{'id': 80, 'name': 'Crime'}, {'id': 28, 'name...",NaN,tt0432047,hi,Sarkar,"The authority of a man, who runs a parallel go...",2.004745,...,7/1/05,123.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Sarkar,"[{'id': 417, 'name': 'corruption'}, {'id': 607...","[{'cast_id': 1, 'character': 'Subhash Nagre (S...","[{'credit_id': '576bae81c3a36864910013fc', 'de...",5900000
2239,2240,"[{'id': 44976, 'name': 'Dhoom Series', 'poster...",19500000,"[{'id': 28, 'name': 'Action'}, {'id': 80, 'nam...",NaN,tt1833673,hi,धूम ३,"To avenge his father's death, a circus enterta...",5.326716,...,12/18/13,172.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dhoom 3,"[{'id': 291, 'name': 'circus'}, {'id': 2492, '...","[{'cast_id': 2, 'character': 'Sahir', 'credit_...","[{'credit_id': '59488707c3a36816c504b523', 'de...",91000000
2251,2252,NaN,130,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt1729637,hi,Bodyguard,Lovely Singh (Salman Khan) is the bodyguard of...,2.402032,...,8/31/11,130.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Bodyguard,"[{'id': 2251, 'name': 'lie'}, {'id': 2913, 'na...","[{'cast_id': 1, 'character': 'Lovely B. Singh'...","[{'credit_id': '52fe48a1c3a368484e102d25', 'de...",8
2287,2288,NaN,18000000,"[{'id': 80, 'name': 'Crime'}, {'id': 18, 'name...",NaN,tt2979920,hi,बॉम्बे वेलवेट,"An ordinary man, who goes against all odds to ...",1.377993,...,5/15/15,151.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Bombay Velvet,"[{'id': 1416, 'name': 'jazz'}, {'id': 2792, 'n...","[{'cast_id': 1, 'character': 'Rosie', 'credit_...","[{'credit_id': '57d00957c3a36866a400269f', 'de...",1500000
2353,2354,NaN,8376800,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",http://www.jodhaaakbar.com/,tt0449994,hi,Jodhaa Akbar,Jodhaa Akbar is a sixteenth century love story...,12.237488,...,2/15/08,213.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Jodhaa Akbar,"[{'id': 1157, 'name': 'wife husband relationsh...","[{'cast_id': 1, 'character': 'Jalaluddin Moham...","[{'credit_id': '52fe45c99251416c75062761', 'de...",13000000
2390,2391,NaN,7500000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",http://www.khattameethathefilm.com/,tt1455811,hi,Khatta Meetha,"Struggling road construction contractor, Sachi...",0.494047,...,7/23/10,155.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Khatta Meetha,"[{'id': 235064, 'name': 'remake of malayalam f...","[{'cast_id': 4, 'character': 'Sachin Tichkule'...","[{'credit_id': '52fe468fc3a36847f8105a21', 'de...",10000000
2436,2437,NaN,4300000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt5946128,hi,Dear Zindagi,An unconventional thinker (Shah Rukh Khan) hel...,3.699552,...,11/24/16,149.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Dear Zindagi,NaN,"[{'cast_id': 8, 'character': 'Kaira', 'credit_...","[{'credit_id': '57c6e9c3c3a3680ba4001c63', 'de...",3376375
2480,2481,NaN,6400000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt2168910,hi,Cocktail,"Gautam is an incorrigible flirt, who runs afte...",7.950488,...,7/13/12,144.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Sometimes good friends may be too good to shar...,Cocktail,"[{'id': 6054, 'name': 'friendship'}, {'id': 97...","[{'cast_id': 7, 'character': 'Veronica Malaney...","[{'credit_id': '52fe4bc8c3a36847f8213af9', 'de...",18800000
2538,2539,NaN,6900000,"[{'id': 10749, 'name': 'Romance'}, {'id': 18, ...",NaN,tt0151150,hi,Josh,Shah Rukh Khan and Sharad Kapoor are the leade...,4.031500,...,6/9/00,162.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Josh,NaN,"[{'cast_id': 1, 'character': 'Max', 'credit_id...","[{'credit_id': '52fe4b82c3a368484e18c7f1', 'de...",15000000
2563,2564,NaN,7400000,"[{'id': 18, 'name': 'Drama'}, {'id': 10749, 'n...",NaN,tt0449999,hi,कभी अलविदा ना कहना,Dev and Maya are both married to different peo...,2.372520,...,8/11/06,193.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,A Love.... That Broke All Relationships,Kabhi Alvida Naa Kehna,"[{'id': 596, 'name': 'adultery'}, {'id': 34094...","[{'cast_id': 1, 'character': 'Dev Saran', 'cre...","[{'credit_id': '52fe45ee9251416c75067637', 'de...",17000000
2567,2568,NaN,11000000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt2424988,hi,Gabbar Is Back,A vigilante network taking out corrupt officia...,1.812728,...,5/1/15,128.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,NaN,Gabbar Is Back,NaN,"[{'cast_id': 1, 'character': 'Professor Aditya...","[{'credit_id': '5792ff149251410d12008917', 'de...",41000000
2807,2808,NaN,5300000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",NaN,tt0439662,hi,Fanaa,Zooni Ali Beg (Kajol) is a blind Kashmiri girl...,3.003526,...,5/26/06,168.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,Destroyed in love...,Fanaa,"[{'id': 1741, 'name': 'blindness and impaired ...","[{'cast_id': 4, 'character': 'Zooni Ali Beg', ...","[{'credit_id': '52fe44aac3a36847f80a3315', 'de...",22175908
2828,2829,NaN,19500000,"[{'id': 10752, 'name': 'War'}, {'id': 36, 'nam...",NaN,tt3735246,hi,Bajirao Mastani,A historical account of the romance between th...,4.683689,...,12/18/15,150.0,"[{'iso_639_1': 'de', 'name': 'Deutsch'}, {'iso...",Released,NaN,Bajirao Mastani,"[{'id': 232174, 'name': '–ª—é–±–æ–≤—å'}, {'id'...","[{'cast_id': 1, 'character': 'Baji Rao I', 'cr...","[{'credit_id': '560b66e0c3a3686814004c7d', 'de...",56000000
2857,2858,NaN,5400000,"[{'id': 53, 'name': 'Thriller'}]",NaN,tt2855648,hi,Madras Cafe,An Indian Intelligence agent journeys into a w...,2.399890,...,8/23/13,130.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}]",Released,Intercept the truth,Madras Cafe,"[{'id': 1990, 'name': 'cupboard'}, {'id': 5299...","[{'cast_id': 2, 'character': 'Vikram Singh', '...","[{'credit_id': '52fe4e08c3a368484e20a8ed', 'de...",6500000
2859,2860,"[{'id': 286951, 'name': 'Singham Collection', ...",3062000,"[{'id': 18, 'name': 'Drama'}, {'id': 28, 'name...",NaN,tt1948150,hi,Singham,A Bollywood classic directed by Rodit Shetty. ...,2.077410,...,7/22/11,143.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Singham,"[{'id': 1721, 'name': 'fight'}, {'id': 13116, ...","[{'cast_id': 1, 'character': 'Bajirao Singham'...","[{'credit_id': '52fe4802c3a368484e0e513f', 'de...",25034000
2959,2960,NaN,2300000,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",NaN,tt1093370,hi,Jab We Met,"Depressed after the passing of his father, Dha...",3.959411,...,10/26/07,145.0,"[{'iso_639_1': 'hi', 'name': 'हिन्दी'}, {'iso_...",Released,NaN,Jab We Met,"[{'id': 2038, 'name': ""love of one's life""}, {...","[{'cast_id': 9, 'character': 'Aditya Kashyap',...","[{'credit_id': '537ef0d8c3a36805a1002844', 'de...",4600000

In [ ]:
df_hindi=df[df['original_language']=='hi']
df_hindi[df_hindi['popularity']==df_hindi['popularity'].max()][['title','popularity','runtime']]

             title  popularity  runtime
2353  Jodhaa Akbar   12.237488    213.0

In [ ]:
df['half_runtime']=df['runtime']/2

In [ ]:
df.head(7)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,runtime,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,93.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,113.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,105.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,122.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,118.0,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,83.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638,41.5
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,92.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075,46.0

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'runtime', 'spoken_languages',
       'status', 'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'half_runtime'],
      dtype='object')

In [ ]:
df['Profit']=df['revenue']-df['budget']

In [ ]:
df.head()

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,spoken_languages,status,tagline,title,Keywords,cast,crew,revenue,half_runtime,Profit
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,-1685349
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,55149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,9792000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,14800000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,"[{'iso_639_1': 'ko', 'name': '한국어/조선말'}]",Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,3923970

In [ ]:
df[df['Profit']==df['Profit'].max()][['title','Profit','runtime']]

          title      Profit  runtime
1761  Furious 7  1316249360    137.0

I want to find the most Profitable film of the Hindi Langauage

In [ ]:
film_hindi = df[df['original_language']=='hi']
film_hindi[film_hindi['Profit']==film_hindi['Profit'].max()][['title','Profit','runtime']]

      title     Profit  runtime
585  Dangal  299600000    161.0

In [ ]:
df_korean = df[df['original_language']=='ko']
df_korean=df_korean[df_korean['Profit']==df_korean['Profit'].max()][['title','Profit','runtime']]

In [ ]:
df_korean = df[df['original_language']=='ko']
df_korean=df_korean[df_korean['Profit']==df_korean['Profit'].max()][['title','Profit']]
print(df_korean)

           title    Profit
147  Snowpiercer  47558912

In [ ]:
film_hindi = df[df['original_language']=='hi']
film_hindi[film_hindi['Profit']==film_hindi['Profit'].max()][['title','Profit','runtime']]

      title     Profit  runtime
585  Dangal  299600000    161.0

We can also drop(remove) the column which we wanted

In [ ]:
df.drop(columns=['runtime'],inplace=True)

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'spoken_languages', 'status',
       'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'half_runtime', 'Profit'],
      dtype='object')

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  spoken_languages       2980 non-null   object
 15  status                 3000 non-null   object
 16  tagline                2403 non-null   object
 17  title                  3000 non-null   object
 18  Keywords               2724 non-null   object
 19  cast                   2987 non-null   object
 20  crew                   2984 non-null   object
 21  revenue                3000 non-null   int64
 22  half_runtime           2998 non-null   float64
 23  Profit                 3000 non-null   int64
dtypes: float64(2), int64(4), object(18)
memory usage: 562.6+ KB

More Basics Operations

In [ ]:
df['Profit'].mean()

np.float64(44194517.77866667)

In [ ]:
df['Profit'].median()

6121122.5

In [ ]:
df['Profit'].mode()

0    0
Name: Profit, dtype: int64

In [ ]:
df['Profit'].sum()

np.int64(132583553336)

use of apply() function

In [ ]:
df['title']

0                         Hot Tub Time Machine 2
1       The Princess Diaries 2: Royal Engagement
2                                       Whiplash
3                                        Kahaani
4                                     Marine Boy
                          ...
2995                                     Chasers
2996                            We Are the Best!
2997                     The Long Kiss Goodnight
2998                            Along Came Polly
2999                                   Abduction
Name: title, Length: 3000, dtype: object

In [ ]:
def convert_upper(column):
  return column.upper()

In [ ]:
df['title_upper']=df['title'].apply(convert_upper)

In [ ]:
df.head(7)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,status,tagline,title,Keywords,cast,crew,revenue,half_runtime,Profit,title_upper
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,Released,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,-1685349,HOT TUB TIME MACHINE 2
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,Released,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,Released,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,9792000,WHIPLASH
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,Released,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,14800000,KAHAANI
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,Released,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,3923970,MARINE BOY
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,Released,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638,41.5,-4738362,PINOCCHIO AND THE EMPEROR OF THE NIGHT
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,Released,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075,46.0,71446075,THE POSSESSION

Lambda Function

In [ ]:
def add_ab(a,b):
  return a+b

In [ ]:
add_ab(10,20)

30

In [ ]:
x= lambda a,b: a+b

In [ ]:
x(10,30)

40

In [ ]:
def new_p(revenue,budget):
  return revenue - budget

In [ ]:
df.columns

Index(['id', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'spoken_languages', 'status',
       'tagline', 'title', 'Keywords', 'cast', 'crew', 'revenue',
       'half_runtime', 'Profit', 'title_upper'],
      dtype='object')

In [ ]:
df['new_profit']=df.apply(lambda x: new_p(x['revenue'],x['budget']),axis=1)

In [ ]:
df.head(7)

,id,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,...,tagline,title,Keywords,cast,crew,revenue,half_runtime,Profit,title_upper,new_profit
0,1,"[{'id': 313576, 'name': 'Hot Tub Time Machine ...",14000000,"[{'id': 35, 'name': 'Comedy'}]",NaN,tt2637294,en,Hot Tub Time Machine 2,"When Lou, who has become the ""father of the In...",6.575393,...,The Laws of Space and Time are About to be Vio...,Hot Tub Time Machine 2,"[{'id': 4379, 'name': 'time travel'}, {'id': 9...","[{'cast_id': 4, 'character': 'Lou', 'credit_id...","[{'credit_id': '59ac067c92514107af02c8c8', 'de...",12314651,46.5,-1685349,HOT TUB TIME MACHINE 2,-1685349
1,2,"[{'id': 107674, 'name': 'The Princess Diaries ...",40000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,tt0368933,en,The Princess Diaries 2: Royal Engagement,Mia Thermopolis is now a college graduate and ...,8.248895,...,It can take a lifetime to find true love; she'...,The Princess Diaries 2: Royal Engagement,"[{'id': 2505, 'name': 'coronation'}, {'id': 42...","[{'cast_id': 1, 'character': 'Mia Thermopolis'...","[{'credit_id': '52fe43fe9251416c7502563d', 'de...",95149435,56.5,55149435,THE PRINCESS DIARIES 2: ROYAL ENGAGEMENT,55149435
2,3,NaN,3300000,"[{'id': 18, 'name': 'Drama'}]",http://sonyclassics.com/whiplash/,tt2582802,en,Whiplash,"Under the direction of a ruthless instructor, ...",64.299990,...,The road to greatness can take you to the edge.,Whiplash,"[{'id': 1416, 'name': 'jazz'}, {'id': 1523, 'n...","[{'cast_id': 5, 'character': 'Andrew Neimann',...","[{'credit_id': '54d5356ec3a3683ba0000039', 'de...",13092000,52.5,9792000,WHIPLASH,9792000
3,4,NaN,1200000,"[{'id': 53, 'name': 'Thriller'}, {'id': 18, 'n...",http://kahaanithefilm.com/,tt1821480,hi,Kahaani,Vidya Bagchi (Vidya Balan) arrives in Kolkata ...,3.174936,...,NaN,Kahaani,"[{'id': 10092, 'name': 'mystery'}, {'id': 1054...","[{'cast_id': 1, 'character': 'Vidya Bagchi', '...","[{'credit_id': '52fe48779251416c9108d6eb', 'de...",16000000,61.0,14800000,KAHAANI,14800000
4,5,NaN,0,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",NaN,tt1380152,ko,마린보이,Marine Boy is the story of a former national s...,1.148070,...,NaN,Marine Boy,NaN,"[{'cast_id': 3, 'character': 'Chun-soo', 'cred...","[{'credit_id': '52fe464b9251416c75073b43', 'de...",3923970,59.0,3923970,MARINE BOY,3923970
5,6,NaN,8000000,"[{'id': 16, 'name': 'Animation'}, {'id': 12, '...",NaN,tt0093743,en,Pinocchio and the Emperor of the Night,"Pinocchio and his friends, a glow worm and a m...",0.743274,...,NaN,Pinocchio and the Emperor of the Night,NaN,"[{'cast_id': 6, 'character': 'Pinocchio (voice...","[{'credit_id': '52fe46f49251416c9106558b', 'de...",3261638,41.5,-4738362,PINOCCHIO AND THE EMPEROR OF THE NIGHT,-4738362
6,7,NaN,14000000,"[{'id': 27, 'name': 'Horror'}, {'id': 53, 'nam...",http://www.thepossessionmovie.com/,tt0431021,en,The Possession,A young girl buys an antique box at a yard sal...,7.286477,...,Fear The Demon That Doesn't Fear God,The Possession,NaN,"[{'cast_id': 23, 'character': 'Clyde', 'credit...","[{'credit_id': '52fe4981c3a368484e12ee29', 'de...",85446075,46.0,71446075,THE POSSESSION,71446075

In [ ]:
df.sort_values('revenue',ascending=False)[['title','revenue','Profit']]

                               title     revenue      Profit
1126                    The Avengers  1519557910  1299557910
1761                       Furious 7  1506249360  1316249360
2770         Avengers: Age of Ultron  1405403694  1125403694
684             Beauty and the Beast  1262886337  1102886337
2322  Transformers: Dark of the Moon  1123746996   928746996
...                              ...         ...         ...
695                        Tere Naam           2           1
1917                 The Merry Widow           1        -591
347          The Wind in the Willows           1         -11
1754                    Mute Witness           1          -1
1874                         Missing           1           1

[3000 rows x 3 columns]

In [ ]:
df.sort_values('Profit',ascending=False)[['title','Profit','revenue']]

                                            title      Profit     revenue
1761                                    Furious 7  1316249360  1506249360
1126                                 The Avengers  1299557910  1519557910
2770                      Avengers: Age of Ultron  1125403694  1405403694
684                          Beauty and the Beast  1102886337  1262886337
2322               Transformers: Dark of the Moon   928746996  1123746996
...                                           ...         ...         ...
776                                     Australia   -80445998    49554002
307                                 Live by Night   -85321445    22678555
251                              Cutthroat Island   -87982678    10017322
2278                 The Adventures of Pluto Nash   -92896027     7103973
2623  Valerian and the City of a Thousand Planets  -107447384    90024292

[3000 rows x 3 columns]

use of date time operations and functions in dataframe

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   object
 14  spoken_languages       2980 non-null   object
 15  status                 3000 non-null   object
 16  tagline                2403 non-null   object
 17  title                  3000 non-null   object
 18  Keywords               2724 non-null   object
 19  cast                   2987 non-null   object
 20  crew                   2984 non-null   object
 21  revenue                3000 non-null   int64
 22  half_runtime           2998 non-null   float64
 23  Profit                 3000 non-null   int64
dtypes: float64(2), int64(4), object(18)
memory usage: 562.6+ KB

In [ ]:
df['release_date']=pd.to_datetime(df['release_date'])

/tmp/ipykernel_1277/642638228.py:1: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['release_date']=pd.to_datetime(df['release_date'])

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     3000 non-null   int64
 1   belongs_to_collection  604 non-null    object
 2   budget                 3000 non-null   int64
 3   genres                 2993 non-null   object
 4   homepage               946 non-null    object
 5   imdb_id                3000 non-null   object
 6   original_language      3000 non-null   object
 7   original_title         3000 non-null   object
 8   overview               2992 non-null   object
 9   popularity             3000 non-null   float64
 10  poster_path            2999 non-null   object
 11  production_companies   2844 non-null   object
 12  production_countries   2945 non-null   object
 13  release_date           3000 non-null   datetime64[ns]
 14  spoken_languages       2980 non-null   object
 15  status                 3000 non-null   object
 16  tagline                2403 non-null   object
 17  title                  3000 non-null   object
 18  Keywords               2724 non-null   object
 19  cast                   2987 non-null   object
 20  crew                   2984 non-null   object
 21  revenue                3000 non-null   int64
 22  half_runtime           2998 non-null   float64
 23  Profit                 3000 non-null   int64
dtypes: datetime64[ns](1), float64(2), int64(4), object(17)
memory usage: 562.6+ KB

In [ ]:
print(df['release_date'][0])

2015-02-20 00:00:00

In [ ]:
print(df['release_date'][0].year)

2015

In [ ]:
print(df['release_date'][90])

2003-10-10 00:00:00

In [ ]:
print(df['release_date'][90].year)

2003

In [ ]:
print(df['release_date'][0].day_name())

Friday

In [ ]:
print(df['release_date'][0].weekday())

4

In [ ]:
df['original_language']

0       en
1       en
2       en
3       hi
4       ko
        ..
2995    en
2996    sv
2997    en
2998    en
2999    en
Name: original_language, Length: 3000, dtype: object

In [ ]:
df['original_language'].unique()

array(['en', 'hi', 'ko', 'sr', 'fr', 'it', 'nl', 'zh', 'es', 'cs', 'ta',
       'cn', 'ru', 'tr', 'ja', 'fa', 'sv', 'de', 'te', 'pt', 'mr', 'da',
       'fi', 'el', 'ur', 'he', 'no', 'ar', 'nb', 'ro', 'vi', 'pl', 'hu',
       'ml', 'bn', 'id'], dtype=object)

In [ ]:
df['original_language'].value_counts()

original_language
en    2575
fr      78
ru      47
es      43
hi      42
ja      37
it      24
ko      20
cn      20
zh      19
de      18
ta      16
sv       8
pt       6
nl       6
fa       5
da       5
ro       4
hu       3
tr       3
no       2
te       2
pl       2
fi       2
ml       2
sr       1
cs       1
mr       1
ar       1
he       1
ur       1
el       1
vi       1
nb       1
bn       1
id       1
Name: count, dtype: int64

In [ ]:
df['original_language'].nunique()

36

In [ ]:
df.isnull().sum()

id                          0
belongs_to_collection    2396
budget                      0
genres                      7
homepage                 2054
imdb_id                     0
original_language           0
original_title              0
overview                    8
popularity                  0
poster_path                 1
production_companies      156
production_countries       55
release_date                0
spoken_languages           20
status                      0
tagline                   597
title                       0
Keywords                  276
cast                       13
crew                       16
revenue                     0
half_runtime                2
Profit                      0
dtype: int64

In [ ]:
print(df['belongs_to_collection'].isnull().sum())

2396

In [ ]:
df['belongs_to_collection'].isnull().sum()

np.int64(2396)

In [ ]:
df['belongs_to_collection'].fillna('Not Present',inplace=True)

/tmp/ipykernel_1277/2051677013.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['belongs_to_collection'].fillna('Not Present',inplace=True)

In [ ]:
df['belongs_to_collection'].isnull().sum()

np.int64(0)